### PR TITLE
Develop faster translation from csv to json-ld

### PR DESCRIPTION
**Pull request by milen-sage**
Changed the info returned from explore_class to include only class-specific properties and parents.
- explore_class method in schema/explorer module called methods 
--- retrieving inherited properties from all parent classes of this class
--- retrieving all parents (recursively) of this class
--- this was slow and retrieving too much information given a multidigraph (as opposed to digraph for which it was initially developed). 

Moved a couple of methods from schema/generator to explorer starting a bit of the refactor we discussed with @BrunoGrandePhD (we can discuss during code review).

Made minor changes to manifest generator to avoid unnecessary function calls to google API; @sujaypatil96 we can discuss during code review.

Made minor changes to the csv_utils module to account for DependOn schema header field in @sujaypatil96 'iterative' csv parser version.

### CODE REVIEW

**Comment by milen-sage** [comment]
@sujaypatil96 could you review this PR when you get a moment?

**Comment by sujaypatil96** [comment]
Yup, absolutely, I'll test/review it now.

**Review by sujaypatil96 — CHANGES_REQUESTED** [review]

**Comment by sujaypatil96** [comment]
I benchmarked the CSV to JSON-LD conversion process on two schemas (`example.model.csv` and `HIV.model.csv`), and the times taken for the two of them were as follows:

1. `example.model.csv`:
 - old parser: 30.29s
 - new parser: 18.36s

2. `HIV.model.csv`:
 - old parser: 11.07s
 - new parser: 2.72s

Thereby confirming a significant speed-up. I will perform the same analysis on `HTAN.model.csv` and update the results here. But for now, it's good to go.🚀

**Comment by milen-sage** [comment]
sounds good! yes, the smaller the schema the smaller the speed up; looking forward to your bench on HTAN schema too!

**Comment by sujaypatil96** [comment]
Comments not critical to this PR, but need to be addressed in the future:

1. Codebase-wide change/transition from using `requiresComponent` to `dependsOnComponent` to ensure consistency/parallel between column/header names in CSV file and corresponding key names in JSON-LD schema (or edge names in networkx graph). For example: change can be made here in `[get_class()](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/utils/csv_utils.py#L84)`. Similarly, changes need to be made in other methods like `[explore_class()](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py#L169)`, etc.

2. To further improve the speed of the parser the following methods that currently operate/work on the JSON-LD schema can be made to work on the networkx graph instead:
 - `[find_class_specific_properties()](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py#L98)`
 - `[find_all_class_properties()](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py#L111)`
 - `[find_class_usages()](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py#L144)`

**Comment by sujaypatil96** [comment]
> sounds good! yes, the smaller the schema the smaller the speed up; looking forward to your bench on HTAN schema too!

@milen-sage: Yup, with a few minor changes that I recommended above, I think the PR is ready to be merged.

**Comment by milen-sage** [comment]
Yes the changes wrt 2) are important for other reasons than speed as well (e.g. having the internal state of schematic completely independent of the input, e.g. json-ld so that we can process potentially other formats (e.g. biolink-ml) relevant for other projects (e.g. INCLUDE).

@sujaypatil96 feel free to merge and open issues for 1 and 2 above; we can prioritize them after the holidays (other refactors and features might take precedence).

**Review by sujaypatil96 — APPROVED** [review]
Approving this PR.🚀

**Comment by milen-sage** [comment]
> `HTAN.model.csv` benchmarking results:
> 
> * old parser: 1609.89s (= 26.83m)
> * new parser: 1164.56s (= 19.4m)
> 
> Approving this PR.🚀

Nice - parser we are replacing > 7 hours

**Pull request merged**
