### PR TITLE
Update schematic dependencies

### PR DESCRIPTION
**Pull request by GiaJordan**
Update dependencies in the `pyproject.toml` to the latest major or minor release to be current and make compatible with `schematic-db`. Also add `schematic-db` to dependencies

### CODE REVIEW

**Comment by GiaJordan** [comment]
@afwillia can we coordinate to test the DCA with the new schematic dependencies?

**Comment by GiaJordan** [comment]
TODO: update api.README.md for library versions

**Comment by linglp** [comment]
@GiaJordan I will need to look into this more. Updating flask version changed `send_from_directory` function that I used in `routes.py` and also the `populate_existing_excel_spreadsheet` function got broken too. I am not sure if I have time to finish trouble shooting this sprint, but I will keep you posted.

**Comment by GiaJordan** [comment]
@linglp thank you! Please let me know if your changed fixed the syntax error when you've had time to run the api tests again.

**Comment by GiaJordan** [comment]
Unable to reproduce failure of `test_in_house_validation` all validation tests are passing on remote and locally with python `3.10.8` and `3.9.13` environments
@milen-sage

**Comment by linglp** [comment]
@GiaJordan The only test that is currently failing now is related to the `model/validate` endpoint for validating manifest as json files format. For some reasons, dependencies update also change the pandas version that I have and `pd.read_json` could no longer read binary files. I tried a couple of other methods but they didn't work. 

@afwillia For this [issue](https://github.com/Sage-Bionetworks/schematic/issues/899), do you remember if we would need to support passing JSON files (or simply passing JSON string would be enough?)?

**Comment by linglp** [comment]
For context, here is a full list of packages that got changed when I switched to this branch and ran `poetry install`: 
```
  • Updating attrs (22.1.0 -> 22.2.0)
  • Updating pyrsistent (0.19.2 -> 0.19.3)
  • Updating traitlets (5.6.0 -> 5.8.1)
  • Updating jsonschema (3.2.0 -> 4.17.3)
  • Updating jupyter-core (4.12.0 -> 5.1.5)
  • Updating pyzmq (24.0.1 -> 25.0.0)
  • Updating jupyter-client (7.4.7 -> 8.0.1)
  • Updating markupsafe (2.0.1 -> 2.1.0)
  • Updating nbformat (5.7.0 -> 5.7.3)
  • Updating bleach (5.0.1 -> 6.0.0)
  • Updating jinja2 (2.11.3 -> 3.1.2)
  • Updating packaging (21.3 -> 23.0)
  • Updating pygments (2.13.0 -> 2.14.0)
  • Updating pyyaml (5.4.1 -> 6.0)
  • Updating terminado (0.17.0 -> 0.17.1)
  • Updating wcwidth (0.2.5 -> 0.2.6)
  • Updating nbconvert (5.5.0 -> 7.2.9)
  • Updating prometheus-client (0.15.0 -> 0.16.0)
  • Updating prompt-toolkit (3.0.33 -> 3.0.36)
  • Updating websocket-client (1.4.2 -> 1.5.0)
  • Updating cachetools (5.2.0 -> 5.3.0)
  • Updating certifi (2022.9.24 -> 2022.12.7)
  • Updating charset-normalizer (2.1.1 -> 3.0.1)
  • Updating debugpy (1.6.4 -> 1.6.6)
  • Updating ipython (7.34.0 -> 8.9.0)
  • Updating jupyter-server (1.15.6 -> 2.1.0)
  • Updating protobuf (4.21.9 -> 4.21.12)
  • Updating urllib3 (1.26.13 -> 1.26.14)
  • Updating google-auth (2.14.1 -> 2.16.0)
  • Updating googleapis-common-protos (1.57.0 -> 1.58.0)
  • Updating importlib-metadata (5.1.0 -> 6.0.0)
  • Updating iniconfig (1.1.1 -> 2.0.0)
  • Updating ipykernel (6.16.2 -> 6.20.2)
  • Updating numpy (1.21.6 -> 1.24.1)
  • Updating pytz (2022.6 -> 2022.7.1)
  • Updating requests (2.28.1 -> 2.28.2)
  • Updating tzdata (2022.6 -> 2022.7)
  • Updating alabaster (0.7.12 -> 0.7.13): Installing...
  • Updating alabaster (0.7.12 -> 0.7.13)
  • Updating click (7.1.2 -> 8.1.3): Installing...
  • Updating google-api-core (2.10.2 -> 2.11.0): Installing...
  • Updating google-api-core (2.10.2 -> 2.11.0): Installing...
  • Updating click (7.1.2 -> 8.1.3)
  • Updating google-api-core (2.10.2 -> 2.11.0): Installing...
  • Updating google-api-core (2.10.2 -> 2.11.0)
  • Updating google-auth-httplib2 (0.0.4 -> 0.1.0)
  • Updating itsdangerous (1.1.0 -> 2.1.2)
  • Updating jupyterlab-widgets (3.0.3 -> 3.0.5)
  • Updating mccabe (0.6.1 -> 0.7.0)
  • Updating nbclassic (0.4.8 -> 0.5.1)
  • Updating pandas (1.3.5 -> 1.5.3)
  • Updating pathspec (0.10.2 -> 0.11.0)
  • Updating pytest (6.2.5 -> 7.2.1)
  • Updating sphinxcontrib-applehelp (1.0.2 -> 1.0.4)
  • Updating uritemplate (3.0.1 -> 4.1.1)
  • Updating werkzeug (1.0.1 -> 2.1.2)
  • Updating widgetsnbextension (4.0.3 -> 4.0.5)
  • Updating altair (4.2.0 -> 4.2.1): Installing...
  • Updating black (20.8b1 -> 22.12.0): Installing...
  • Updating coverage (6.5.0 -> 7.1.0): Installing...
  • Updating coverage (6.5.0 -> 7.1.0)
  • Updating cryptography (38.0.4 -> 39.0.0): Installing...
  • Updating cryptography (38.0.4 -> 39.0.0)
  • Updating coverage (6.5.0 -> 7.1.0)
  • Updating cryptography (38.0.4 -> 39.0.0)
  • Updating black (20.8b1 -> 22.12.0)
  • Updating coverage (6.5.0 -> 7.1.0)
  • Updating cryptography (38.0.4 -> 39.0.0)
  • Updating black (20.8b1 -> 22.12.0)
  • Updating coverage (6.5.0 -> 7.1.0)
  • Updating cryptography (38.0.4 -> 39.0.0)
  • Updating altair (4.2.0 -> 4.2.1)
  • Updating black (20.8b1 -> 22.12.0)
  • Updating coverage (6.5.0 -> 7.1.0)
  • Updating cryptography (38.0.4 -> 39.0.0)
  • Updating flask (1.1.4 -> 2.1.3)
  • Updating google-api-python-client (1.12.11 -> 2.74.0)
  • Updating google-auth-oauthlib (0.4.6 -> 0.8.0)
  • Updating ipywidgets (8.0.2 -> 8.0.4)
  • Updating networkx (2.6.3 -> 2.8.8)
  • Updating pdoc (12.3.0 -> 12.3.1)
  • Updating pycodestyle (2.7.0 -> 2.10.0)
  • Updating pydantic (1.10.2 -> 1.10.4)
  • Updating pyflakes (2.3.1 -> 3.0.1)
  • Updating setuptools (52.0.0 -> 66.1.1)
  • Updating scipy (1.7.3 -> 1.10.0)
  • Updating sphinx (5.1.1 -> 6.1.3)
  • Updating click-log (0.3.2 -> 0.4.0)
  • Updating connexion (2.14.1 -> 2.14.2)
  • Updating dateparser (1.1.4 -> 1.1.6)
  • Updating flake8 (3.9.2 -> 6.0.0)
  • Updating graphviz (0.16 -> 0.20.1)
  • Updating great-expectations (0.15.34 -> 0.15.46)
  • Updating oauth2client (3.0.0 -> 4.1.3)
  • Updating pygsheets (2.0.5 -> 2.0.6)
  • Updating pytest-cov (2.12.1 -> 4.0.0)
  • Updating python-dotenv (0.15.0 -> 0.21.1)
  • Updating rdflib (5.0.0 -> 6.2.0)
  • Updating sphinx-click (3.1.0 -> 4.4.0)

```

**Comment by linglp** [comment]
> @GiaJordan The only test that is currently failing now is related to the `model/validate` endpoint for validating manifest as json files format. For some reasons, dependencies update also change the pandas version that I have and `pd.read_json` could no longer read binary files. I tried a couple of other methods but they didn't work.
> 
> @afwillia For this [issue](https://github.com/Sage-Bionetworks/schematic/issues/899), do you remember if we would need to support passing JSON files (or simply passing JSON string would be enough?)?
> 
> For more context: this answer [here](https://stackoverflow.com/questions/71074363/pandas-read-json-behavior-with-bytes-object) seems to have similar problem that I have. But I tried `BytesIO` and it didn't work



> @GiaJordan The only test that is currently failing now is related to the `model/validate` endpoint for validating manifest as json files format. For some reasons, dependencies update also change the pandas version that I have and `pd.read_json` could no longer read binary files. I tried a couple of other methods but they didn't work.
> 
> @afwillia For this [issue](https://github.com/Sage-Bionetworks/schematic/issues/899), do you remember if we would need to support passing JSON files (or simply passing JSON string would be enough?)?
> 
> For more context: this answer [here](https://stackoverflow.com/questions/71074363/pandas-read-json-behavior-with-bytes-object) seems to have similar problem that I have. But I tried `BytesIO` and it didn't work

I just noticed that when I did `poetry install` using the develop branch, pandas also got updated to 1.5.3, so the `develop` branch also has this functionalities failed. If that's the case, I could open a new issue to debug the `read_json` function.

**Comment by GiaJordan** [comment]
@linglp yes, in the `develop` .toml the pandas spec would allow for that version, and it's been unchanged in this PR. I think opening another ticket is a good idea

**Review by linglp — APPROVED** [review]

**Pull request merged**
