### PR TITLE
Minor updates to schema reflecting requests for 1st HTAN data release

### PR DESCRIPTION
**Pull request by milen-sage**
One last update @xdoan ? :)

### CODE REVIEW

**Comment by milen-sage** [comment]
if not, @sujaypatil96 can incorporate into the DC app after it is transferred to his shiny account.

**Comment by xdoan** [comment]
I'm happy to do it but it'll probably get done by tomorrow as I have a lot of meetings

**Comment by xdoan** [comment]
@milen-sage can you share which templates affects is in so I can make sure I test the right ones?

**Comment by milen-sage** [comment]
The addition of file formats affects all assay data templates, but you can just test with one. The other one is biospecimen. Thanks!

**Comment by xdoan** [comment]
Are you able to generate all the templates? Just spot checking but can't generate scRNAseq level 1 or 2 or minimal metadata due to some "KeyError: 'displayName'" but I wasn't aware of any changes in the display/schema names. @milen-sage

**Comment by milen-sage** [comment]
hmm... thanks for the check; let me see on my end

**Comment by milen-sage** [comment]
ok - got the error; will commit in a bit

**Comment by milen-sage** [comment]
@xdoan the error should be fixed w/ the latest commit - good catch!

Schema label for Other Assay is OtherAssay.

**Comment by xdoan** [comment]
yup looks like the cell am format was conflicting, I was already using the OtherAssay schema name in the config and its all resolved now!

**Review by xdoan — APPROVED** [review]

**Pull request merged**
