### PR TITLE
allow users to upload csv or json file when submitting manifest using API endpoints

### PR DESCRIPTION
**Pull request by linglp**
This PR is related to the issue mentioned [here](https://github.com/Sage-Bionetworks/schematic/issues/900). Users could now upload json file when submitting a manifest using the API endpoint

### CODE REVIEW

**Comment by afwillia** [comment]
Looks good to me! Works with the app. Thank you!

**Review by afwillia — APPROVED** [review]

**Comment by afwillia** [comment]
@linglp for develop-ManifestjsonEndpoint can you confirm if file_type argument to validate_manfest_route accepts a string in JSON format or is it a .json file? Screen Shot 2022-09-20 at 4 12 29 PM

Also, will the validation endpoint be updated to accept a JSON string instead of attaching a csv file, too?

**Comment by linglp** [comment]
note to myself: the endpoint will need to accept json string instead of file

**Comment by afwillia** [comment]
@linglp when I pull the changes and run `python run_api.py` I get the following error

```
File ".../schematic/api/routes.py", line 430, in <module>
    ) -> list[str]:
TypeError: 'type' object is not subscriptable
```

**Review by afwillia — APPROVED** [review]
LGTM!

**Review by andrewelamb — APPROVED** [review]

**Pull request merged**
