### PR TITLE
feat/technical debt: added trivy code scan to schematic repo

### PR DESCRIPTION
**Pull request by linglp**
## Context
Schematic in the past used github dependabot to scan security vulnerabilities but it is not working well because poetry version was overwritten in the toml file: 

Screenshot 2024-06-25 at 1 02 03 PM

This is a known issue: https://github.com/dependabot/dependabot-core/issues/1556 

To make sure that we follow Sage's [SLDC process](https://sagebionetworks.jira.com/wiki/spaces/SISP/pages/831127563/Software+Development+Lifecycle+Standard), we are thinking of using an alternative way to scan security risks. 

Please also note that Vulnerabilities should be managed based on the documentation here: [Atlassian Cloud](https://sagebionetworks.jira.com/wiki/spaces/SISP/pages/831193216/Vulnerability+Management+Process)

## Changes 
* Borrowed the trivy scan workflow from mono repo and added it for schematic
*  updated to use codeql-action v3 because v2 will be deprecated end of 2024: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2

### CODE REVIEW

**Comment by andrewelamb** [comment]
@linglp Is there a related jira issue?

**Comment by linglp** [comment]
> @linglp Is there a related jira issue?



> @linglp Is there a related jira issue?

No.. I don't have a jira issue related to it. i could write one if needed.

**Review by tschaffter — APPROVED** [review]

**Review by GiaJordan — APPROVED** [review]
LGTM

**Comment by MiekoHash** [comment]
@linglp Same question as @andrewelamb  - Which JIRA ticket tracks this PR?

**Comment by linglp** [comment]
@MiekoHash To clarify, the use of the Trivy scan was decided during BE stack meeting as a replacement for Dependabot, based on the need to adhere to Sage's SLDC process for identifying security risks. I implemented this change in line with that decision.

Regarding creating tickets, I believe it adds unnecessary overhead to the dev workflow since this is a relatively small change . If there's a specific issue with the Trivy scan or something you'd like me to address, feel free to create an issue, and I'll prioritize it accordingly.

**Comment by tschaffter** [comment]
@brucehoff Does the Synapse team have a Standard Operating Procedure (SOP) for addressing vulnerabilities reported by tools like Trivy and Sonar? It seems like with a little effort, we could raise awareness across all technology teams and encourage them to adopt such a procedure. This could help improve security practices across the board.

**Comment by brucehoff** [comment]
@tschaffter Sage's [SDLC](https://sagebionetworks.jira.com/wiki/spaces/SISP/pages/831127563/Software+Development+Lifecycle+Standard) calls for continuous security testing.  Our [Vulnerability Management Work Instructions](https://sagebionetworks.jira.com/wiki/spaces/SISP/pages/2617540708/Vulnerability+Management+Work+Instructions) mentions Dependabot but not Trivy or Sonar.  The specific 'SOP' followed by the Synapse team most relevant to your question is [here](https://sage-bionetworks.github.io/Synapse-Stack-Review-Agenda/stack-release.html).

**Pull request merged**
