### PR TITLE
feat: Add dev container

### LINKED ISSUE #1059: Uniformize developer experience using Visual Studio Code Dev Containers
**Is your feature request related to a problem? Please describe.**

- Problem 1: The developers use different development environment with different tool versions. For example, the README asks developers to install `poetry` manually but does not specify which version to install. Different development environment may lead to different tool output.
- Problem 2: The developer need to install tools manually (e.g. poetry). This step can automated.

**Describe the solution you'd like**

Uniformize developer tooling using a dev container (see [dev container standard](https://containers.dev/)).

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Using a dev container would make it easier for developer to potentially use the computation caching feature of Nx for the sake of saving time on tasks such as lint, build and test (tracked in separate ticket).

### PR DESCRIPTION
**Pull request by tschaffter**
Fixes #1059

## Changelog

- Add the definition of a dev container that includes Python and Poetry among other tools.
  - See the [dev container standard](https://containers.dev/) for more information.
  - The dev container image is adapted from the dev container used in https://github.com/Sage-Bionetworks/challenge-registry
  - The dev container includes tools such as Node.js and Java, which should be useful for API/web development and in following PRs I may submit regarding speeding up CI/CD workflow.
- Add the folder `tools/` with the script required to build the dev container image [sagebionetworks/schematic-devcontainer](https://hub.docker.com/repository/docker/sagebionetworks/schematic-devcontainer).
  - See section "Future work" below.
- Define `workspace-*` commands in `dev-env.sh`.
  - E.g. `workspace-install` to install the project dependencies.
- Add a badge to the README to enable developers to start the development environment with VS Code with a single click (click > VS Code starts the dev container > developer is ready to develop).
  - This badge will only work once this PR is merged to the base branch.

### Develop inside the dev container with VS Code

1. Launch VS Code
2. Install the VS Code extension [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
3. Open the folder of this repository
4. Checkout the branch behind this PR
5. Open the Command Palette (`Ctrl+Shift+P`)
6. Type "dev" > select "Dev Containers: Open Folder in Container..." > OK
7. You are now inside the dev container with all the tools required to contribute to this project.
    - Try `python --version` and `poetry --version`

image

### Develop inside a GitHub Codespace

GitHub Codespace is a new feature that was released in November 2022. It relies on the dev container standard to spin up a development environment for projects that include a dev container definition. You can try starting a GH Codespace using the branch behind this PR.

1. Go to https://github.com/tschaffter/schematic/tree/add-devcontainer
2. Click on the Code button
3. Click on the tab "Codespaces"
4. Click on the button "Create codespace on add-devcontainer" (add-devcontainer is the name of the branch).
5. You are now inside the codespace

image

image

## Future Work

- Build and publish the dev container image with a GitHub workflow.
- Update CI/CD workflows to perform operations inside the dev container.

### CODE REVIEW

**Comment by tschaffter** [comment]
This PR does not change the code of schematic so I'm not sure why the tests are failing.

**Comment by milen-sage** [comment]
@tschaffter I think tests fail because the request is from a different fork. I wouldn't worry about that, unless you'd like to :)

**Comment by milen-sage** [comment]
Just to confirm, @tschaffter the goal of this request - in addition to the various other features of the dev container - is to speed up CI/CD actions?

**Comment by milen-sage** [comment]
@GiaJordan could you review this PR. I think we can evaluate it and merge it next year.

**Comment by tschaffter** [comment]
> the goal of this request - in addition to the various other features of the dev container - is to speed up CI/CD actions?

@milen-sage Yes, among other benefits to your team.

**Comment by tschaffter** [comment]
Following a discussion with Milen, I should have the chance to present to the FAIR Data team the benefits of developing inside a dev container early next year.

**Comment by thomasyu888** [comment]
This could be a good retrospective topic to implement this as a practice when developing

**Comment by andrewelamb** [comment]
Its looking we'll move this or the next verison into the monorepo anyway.

**Pull request closed without merging**
