### PR TITLE
Biospecimen corrections 

### PR DESCRIPTION
**Pull request by milen-sage**
addressing https://github.com/sage-bionetworks/htan-coordination/issues/193

### CODE REVIEW

**Review by xdoan — APPROVED** [review]
technically works, asked Nithya to review contents again.

**Comment by milen-sage** [comment]
@xdoan hmm could you double check that the jsonld schema from this PR was deployed on the dev environment and the latest spreadsheet linked in https://github.com/Sage-Bionetworks/schematic/pull/304 was generated using this latest schema?

For example, in the json-ld in this PR I see Adjacent Biospecimen ID is optional, but in the spreadsheet^  it is required. Similarly for fiducial marker we have different valid values in the spreadsheet^ compared to what's in the json-ld schema; same for the other changes. The spreadsheet^ was generated using the older schema.

**Comment by xdoan** [comment]
this is in my git log, how else should I check?
```
commit d2dae4f4208ca47415e7910f8867ae4d991967dd (HEAD -> milen-sage-develop-schema-update, origin/main, main)
Merge: f969b10 f88f7d9
Author: Xengie Doan <xengie.doan@sagebase.org>
Date:   Thu Oct 8 14:06:42 2020 -0700

    Merge pull request #304 from milen-sage/develop-schema-update
    
    Biospecimen corrections

commit f88f7d9f4883b837c854a3a4e3ef7fb90e600c6e
Author: Milen Nikolov <milen.nikolov@sagebase.org>
Date:   Thu Oct 8 10:42:49 2020 -0700

    Biospecimen corrections addressing https://github.com/sage-bionetworks/htan-coordination/issues/193
```

**Comment by milen-sage** [comment]
If you open up the json-ld that the app is configured to use, do you see 

{
            "@id": "bts:AdjacentBiospecimenID",
            "@type": "rdfs:Class",
            "rdfs:comment": "List of HTAN Identifiers (separated by commas) of adjacent biospecimens cut from the same sample; for example HTA3_3000_3, HTA3_3000_4, ...",
            "rdfs:label": "AdjacentBiospecimenID",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:Biospecimen"
                }
            ],
            "schema:isPartOf": {
                "@id": "http://schema.biothings.io"
            },
            "sms:displayName": "Adjacent Biospecimen ID",
            **"sms:required": "sms:false",**
            "sms:validationRules": []
        }

And overall is the json-ld schema the app uses the same as https://raw.githubusercontent.com/milen-sage/schematic/f88f7d9f4883b837c854a3a4e3ef7fb90e600c6e/data/schema_org_schemas/HTAN.jsonld

**Pull request merged**
