### PR TITLE
v23.9.2

### PR DESCRIPTION
**Pull request by andrewelamb**
### Features:
- #1289 

### Bugs fixed:
- #1285
- #1287
- #1290

### CODE REVIEW

**Comment by andrewelamb** [comment]
@AmyHeiser It looks like everything descrive [here](https://sagebionetworks.jira.com/projects/FDS/versions/34283/tab/release-report-all-issues) has been merged into develop.

@GiaJordan @mialy-defelice Is there anything else that we would want to add to this release? If not it seems like it's ready to be tested.

**Review by GiaJordan — APPROVED** [review]
## Testing Report

### Pytest
The tests skipped on GH actions were run, excluding the api benchmarking tests. 3 were failing:
```
FAILED tests/test_manifest.py::TestManifestGenerator::test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay]
FAILED tests/test_api.py::TestSynapseStorage::test_get_dataset_files[None-False]
FAILED tests/test_api.py::TestManifestOperation::test_download_access_restricted_manifest
```
I think we can proceed with the release in spite of these failures.

The first test should have been updated as part of a previous PR where a manifest column was removed, but the failure wasn't raised because the test wasn't run as part of our automated testing. @Mialy DeFelice has opened an [issue](https://sagebionetworks.jira.com/browse/FDS-1047) to remedy.

For the 2nd test I'm not sure if what is failing should be the intended behavior; it seems like the failure is because tables are not being returned in the list of files. Inspecting it shows that nothing besides files are returned in the response which is what I would expect the desired behavior to be. [Issue](https://sagebionetworks.jira.com/browse/FDS-1143).

For the 3rd, the entity on synapse no longer has access restrictions in place that the test expects so it is failing. [Issue](https://sagebionetworks.jira.com/browse/FDS-1144).

These are minor failures that aren't related to the changes in this release so proceeding seems safe.

### CLI
Manifest submission from the CLI worked as expected. `-mrt table_file_and_entities` was not tested due to previously identified issues. Manifest submission worked fine.

### API
All API endpoints are working as expected. `/model/submit` was tested with the different values for `-mrt` excluding `table_file_and_entities` because of the aforementioned issue. One thing to note is that if you're uploading a manifest with -mrt set to file_only but the manifest has the entityId of the table in the entityId column then the table will still be updated. We should probably document that somewhere @AmyHeiser or change the behavior if that's not intended.

**Overall we're good to proceed with the release of schematic `v23.9.2`**

**Comment by MiekoHash** [comment]
@GiaJordan Thank you for the nice summary. Is there a reason why https://github.com/Sage-Bionetworks/schematic/pull/1290 is not listed under Bugs fixed? Is it bundled with something else?

**Comment by andrewelamb** [comment]
@MiekoHash My, fault there was a typo in the notes, and I added the wrong issue.

**Comment by MiekoHash** [comment]
Ah, great, thanks, @andrewelamb . @AmyHeiser This release is ready for your review. I tagged you on [this small fix](https://sagebionetworks.jira.com/browse/FDS-1026?focusedCommentId=184347). Thanks everyone.

**Comment by andrewelamb** [comment]
@AmyHeiser @MiekoHash @milen-sage @mialy-defelice 
This was renamed to v23.9.3 due to the workflow issues.

**Pull request merged**
