### PR TITLE
Fix formatting issues when pulling data from Synapse to Excel Manifest

### PR DESCRIPTION
**Pull request by mialy-defelice**
Fix for [FDS-463](https://sagebionetworks.jira.com/browse/FDS-463).

**Description**
The issue here was that pulling and Excel manifest with Data from Synapse the formatting of the sheet was lost. This is an issue with how Excel handles formatting when replacing data. To fix I have left the column headers in place and adding data cell by cell.  Additional columns are added and formatted as needed as well. 

**To Test**
Pull data from Synapse into for a manifest using Excel output. Note that formatting remains. An example command would be:
```
schematic manifest -c config.yml get  -dt Demographics -p HTAN.model.jsonld -d syn22677299 -oxlsx test_demographics_bu.xlsx
```

```
schematic manifest -c config.yml get -dt ScRNA-seqLevel1 -p HTAN.model.jsonld -d syn23665337 --output_xlsx test_scrnaseq_with_annotations_htan.xlsx -a
```

[FDS-463]: https://sagebionetworks.jira.com/browse/FDS-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by linglp** [comment]
@mialy-defelice overall the code looks good. Thanks for the fix. I used schematic api manifest/generate to test it out, and when I opened the manifest in libra office, the formatting is a little bit off: 
Screen Shot 2023-06-13 at 3 12 37 PM

Do you know if this is expected? The font of `Test New column` is `Cambria` while the rest of the column uses `Arial`.

**Comment by linglp** [comment]
Note: 
HTAN data model to use: https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld
asset view: syn22125563

**Comment by linglp** [comment]
The font size issue could be reproduced by using the following parameters to trigger `manifest/generate`: 
* schema_url: https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld
* data_type: Demographics
* dataset_id: syn22677299
* asset_view: syn22125563
* output_format: excel

**Comment by mialy-defelice** [comment]
> * syn22125563

Does not reproduce when using Office 365, would probably need to use Libre Office to reproduce.

**Comment by linglp** [comment]
> > * syn22125563
> 
> Does not reproduce when using Office 365, would probably need to use Libre Office to reproduce.

Thanks Mialy! Good to know that this is only a office 365 issue.

**Review by linglp — APPROVED** [review]
Looks good.

**Pull request merged**
