### PR TITLE
Schematic `v23.11.1`

### PR DESCRIPTION
**Pull request by GiaJordan**
## Bug Fixes

- #1291
- #1303
- #1311 
- #1312 
- #1319 

## New Features

- #1259 
- #1286
- #1302 

## Maintenance

- #1223 
- #1288
- #1300
- #1314 
- #1316
- #1322

### CODE REVIEW

**Comment by GiaJordan** [comment]
@andrewelamb `RC23.10.1` is ready for testing. Please let me know if you experience any inconsistent behavior with the tests during your process.

**Comment by andrewelamb** [comment]
@GiaJordan Thanks! 

I'll run the tests listed in the jira issue locally.

I recall that someone was going to come up with a list of of CLI commands to run and test. Did that get done?

For the API do I just fire up swagger and run the examples or is there a list of things to test as well?

**Comment by andrewelamb** [comment]
`pytest -m google_credentials_needed`:
One test failed

```
tests/test_manifest.py::TestManifestGenerator::test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay] FAILED
>       assert is_file_based == ("eTag" in output)
E       AssertionError: assert True == ('eTag' in                                   Filename Sample ID  ... Genome FASTA     entityId\n0  TestDataset-Annotations-v3/Sample_A.txt            ...               syn25614636\n1  TestDataset-Annotations-v3/Sample_B.txt            ...               syn25614637\n2  TestDataset-Annotations-v3/Sample_C.txt            ...               syn25614638\n\n[3 rows x 7 columns])

tests/test_manifest.py:136: AssertionError
```

**Comment by andrewelamb** [comment]
`pytest -m rule_combos`
All passed

**Comment by GiaJordan** [comment]
@andrewelamb the RC is ready for testing

**Comment by GiaJordan** [comment]
@andrewelamb All PRs have been merged that should be included in this release. There are no more foreseen issues that need to be addressed as part of this release. The RC is ready for more in-depth testing when this round of actions pass.
cc @AmyHeiser

**Comment by andrewelamb** [comment]
While running these tests:
`pytest -m google_credentials_needed`

This test failed:
`tests/test_manifest.py::TestManifestGenerator::test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay] FAILED`

```
________________________________ TestManifestGenerator.test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay] _________________________________

self = <tests.test_manifest.TestManifestGenerator object at 0x7fb40e0bb7c0>
manifest = (                                  Filename Sample ID File Format         Component Genome Build Genome FASTA     enti...C.txt                        BulkRNA-seqAssay                            syn25614638, False, 'BulkRNA-seqAssay', False)

    @pytest.mark.google_credentials_needed
    def test_get_manifest_first_time(self, manifest):
    
        # See parameterization of the `manifest_generator` fixture
        output, use_annotations, data_type, sheet_url = manifest
    
        if sheet_url:
            logger.debug(output)
            assert isinstance(output, str)
            assert output.startswith("https://docs.google.com/spreadsheets/")
            return
    
        # Beyond this point, the output is assumed to be a data frame
    
        # Update expectations based on whether the data type is file-based
        is_file_based = data_type in ["BulkRNA-seqAssay"]
    
        assert "Component" in output
>       assert is_file_based == ("eTag" in output)
E       AssertionError: assert True == ('eTag' in                                   Filename Sample ID  ... Genome FASTA     entityId\n0  TestDataset-Annotations-v3/Sample_A.txt            ...               syn25614636\n1  TestDataset-Annotations-v3/Sample_B.txt            ...               syn25614637\n2  TestDataset-Annotations-v3/Sample_C.txt            ...               syn25614638\n\n[3 rows x 7 columns])

tests/test_manifest.py:136: AssertionError
```

**Comment by andrewelamb** [comment]
For this CLI test:
`schematic manifest --config ~/path/to/config.yml get --dataset_id syn25614635 --data_type BulkRNA-seqAssay --sheet_url --use_annotations`
The generated link and the example's columns were in a different order

**Comment by andrewelamb** [comment]
This command:
`schematic manifest --config ~/path/to/config.yml get --output_xlsx 'test-example.xlsx' --dataset_id syn52746566`
resulted in warnings:

```
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
warning: See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
warning:   return np.find_common_type(types, [])
[WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
warning: See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
warning:   return np.find_common_type(types, [])
```

**Comment by andrewelamb** [comment]
For these tests:
`pytest -m schematic_api`
The test stopped running at:
`tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Match at Least values]`
It hung on this test for ~1 hr

In addition there were several failures before getting to that point:

```
FAILED tests/test_api.py::TestSynapseStorage::test_get_dataset_files[None-False] - AssertionError: assert (['syn25705259', 'Boolean Test'] and ['syn23667202', 'DataTypeX_table'] in [['syn23643259', 'credentials.json'], ['syn25171627', 'schema...
FAILED tests/test_api.py::TestSchemaVisualization::test_visualize_component[Patient-Component,Component,TBD,False,,,,Patient] - assert 'Component,Component,TBD,False,,,,Patient' in 'Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component\nYear of Bi...
FAILED tests/test_api.py::TestSchemaVisualization::test_visualize_component[BulkRNA-seqAssay-Component,Component,TBD,False,,,,BulkRNA-seqAssay] - assert 'Component,Component,TBD,False,,,,BulkRNA-seqAssay' in 'Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component\nS...
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check List] - assert 6.53889060599613 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Regex List] - assert 5.337248218995228 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Regex Single] - assert 5.819476903001487 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Num] - assert 5.681331515996135 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Float] - assert 6.071253260000958 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Int] - assert 6.524870522000128 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check String] - assert 8.326836131003802 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check URL] - assert 238.23725233000005 < 5.0
FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Match at Least] - assert 14.186843691000831 < 5.0
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by andrewelamb** [comment]
This CLI test:
`schematic model --config config_example.yml validate --manifest_path tests/data/mock_manifests/Valid_Test_Manifest.csv --data_type MockComponent --project_scope syn23643250`

Resulted in quite a few warnings and some errors:
```
FileDataContext loading zep config
GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
GxConfig.parse_yaml() returning empty `xdatasources`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
FileDataContext loading zep config
GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
GxConfig.parse_yaml() returning empty `xdatasources`
Loading 'datasources' ->
{}
Loaded 'datasources' ->
{}
```
It say at the end it validated without errors
`Your manifest has been validated successfully. There are no errors in your manifest, and it can be submitted without any modifications.`
So that seems contradictory

**Comment by GiaJordan** [comment]
> While running these tests: `pytest -m google_credentials_needed`
> 
> This test failed: `tests/test_manifest.py::TestManifestGenerator::test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay] FAILED`
> 
> ```
> ________________________________ TestManifestGenerator.test_get_manifest_first_time[data_frame-skip_annotations-BulkRNAseqAssay] _________________________________
> 
> self = <tests.test_manifest.TestManifestGenerator object at 0x7fb40e0bb7c0>
> manifest = (                                  Filename Sample ID File Format         Component Genome Build Genome FASTA     enti...C.txt                        BulkRNA-seqAssay                            syn25614638, False, 'BulkRNA-seqAssay', False)
> 
>     @pytest.mark.google_credentials_needed
>     def test_get_manifest_first_time(self, manifest):
>     
>         # See parameterization of the `manifest_generator` fixture
>         output, use_annotations, data_type, sheet_url = manifest
>     
>         if sheet_url:
>             logger.debug(output)
>             assert isinstance(output, str)
>             assert output.startswith("https://docs.google.com/spreadsheets/")
>             return
>     
>         # Beyond this point, the output is assumed to be a data frame
>     
>         # Update expectations based on whether the data type is file-based
>         is_file_based = data_type in ["BulkRNA-seqAssay"]
>     
>         assert "Component" in output
> >       assert is_file_based == ("eTag" in output)
> E       AssertionError: assert True == ('eTag' in                                   Filename Sample ID  ... Genome FASTA     entityId\n0  TestDataset-Annotations-v3/Sample_A.txt            ...               syn25614636\n1  TestDataset-Annotations-v3/Sample_B.txt            ...               syn25614637\n2  TestDataset-Annotations-v3/Sample_C.txt            ...               syn25614638\n\n[3 rows x 7 columns])
> 
> tests/test_manifest.py:136: AssertionError
> ```

This is a known issue with a ticket logged already

**Comment by GiaJordan** [comment]
> For this CLI test: `schematic manifest --config ~/path/to/config.yml get --dataset_id syn25614635 --data_type BulkRNA-seqAssay --sheet_url --use_annotations` The generated link and the example's columns were in a different order

I'll defer to @linglp and @mialy-defelice on severity

**Comment by GiaJordan** [comment]
> For this CLI test: `schematic manifest --config ~/path/to/config.yml get --output_xlsx 'test-example.xlsx' --dataset_id syn52746566` resulted in warnings:
> 
> ```
> See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
>   return np.find_common_type(types, [])
> 
> warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
> warning: See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
> warning:   return np.find_common_type(types, [])
> [WARNING] /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
> See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
>   return np.find_common_type(types, [])
> 
> warning: /home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
> warning: See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
> warning:   return np.find_common_type(types, [])
> ```

I don't think this should prevent the release, but we should open an issue to update what has been deprecated

**Comment by GiaJordan** [comment]
> This CLI test: `schematic model --config config_example.yml validate --manifest_path tests/data/mock_manifests/Valid_Test_Manifest.csv --data_type MockComponent --project_scope syn23643250`
> 
> Resulted in quite a few warnings and some errors:
> 
> ```
> FileDataContext loading zep config
> GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
> GxConfig.parse_yaml() returning empty `xdatasources`
> Loading 'datasources' ->
> {}
> Loaded 'datasources' ->
> {}
> FileDataContext loading zep config
> GxConfig.parse_yaml() failed with errors - [{'loc': ('xdatasources',), 'msg': 'field required', 'type': 'value_error.missing'}]
> GxConfig.parse_yaml() returning empty `xdatasources`
> Loading 'datasources' ->
> {}
> Loaded 'datasources' ->
> {}
> ```
> 
> It say at the end it validated without errors `Your manifest has been validated successfully. There are no errors in your manifest, and it can be submitted without any modifications.` So that seems contradictory

The "without errors" refers to validation errors specifically. These messages have to do with GX processes.
I don't think this should block the release, but we should do one more check to confirm*. We're quite behind on our GX version and some things have already started changing or being deprecated. There's an issue open to update. Could you either create a new one with this message or add it to the existing one?

@andrewelamb *Do the manifest validation tests pass when run locally still? We just need to make sure that all the expected errors and warnings are still being generated. If they are all present then this isn't a blocker.

@AmyHeiser this has the potential to be a big issue in the future. If we get too out of date on GX it has the potential to break a significant portion of the validation rules. We'd either have to scramble to update or lock the versions to restrict allowable versions of the package.

**Comment by andrewelamb** [comment]
> @andrewelamb *Do the manifest validation tests pass when run locally still? We just need to make sure that all the expected errors and warnings are still being generated. If they are all present then this isn't a blocker.

Yes besides the quoted error message, everything is running as it the doc described. (Perhaps the doc could be clearer?)

**Comment by GiaJordan** [comment]
> For these tests: `pytest -m schematic_api` The test stopped running at: `tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Match at Least values]` It hung on this test for ~1 hr
> 
> In addition there were several failures before getting to that point:
> 
> ```
> FAILED tests/test_api.py::TestSynapseStorage::test_get_dataset_files[None-False] - AssertionError: assert (['syn25705259', 'Boolean Test'] and ['syn23667202', 'DataTypeX_table'] in [['syn23643259', 'credentials.json'], ['syn25171627', 'schema...
> FAILED tests/test_api.py::TestSchemaVisualization::test_visualize_component[Patient-Component,Component,TBD,False,,,,Patient] - assert 'Component,Component,TBD,False,,,,Patient' in 'Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component\nYear of Bi...
> FAILED tests/test_api.py::TestSchemaVisualization::test_visualize_component[BulkRNA-seqAssay-Component,Component,TBD,False,,,,BulkRNA-seqAssay] - assert 'Component,Component,TBD,False,,,,BulkRNA-seqAssay' in 'Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component\nS...
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check List] - assert 6.53889060599613 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Regex List] - assert 5.337248218995228 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Regex Single] - assert 5.819476903001487 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Num] - assert 5.681331515996135 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Float] - assert 6.071253260000958 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Int] - assert 6.524870522000128 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check String] - assert 8.326836131003802 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check URL] - assert 238.23725233000005 < 5.0
> FAILED tests/test_api.py::TestValidationBenchmark::test_validation_performance[Check Match at Least] - assert 14.186843691000831 < 5.0
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ```

The `TestValidationBenchmark` are currently expected to fail because we've not yet optimized for performance.
@AmyHeiser The test plan should be amended to exclude the `rule_benchmark` marked tests in `test_api.py`
@andrewelamb can you re-run with this exclusion?

I'm not sure why the one test hangs, we can open an issue for that @AmyHeiser ?

**Comment by GiaJordan** [comment]
> > @andrewelamb *Do the manifest validation tests pass when run locally still? We just need to make sure that all the expected errors and warnings are still being generated. If they are all present then this isn't a blocker.
> 
> Yes besides the quoted error message, everything is running as it the doc described. (Perhaps the doc could be clearer?)

Cool, I think this is okay to release then

**Review by andrewelamb — APPROVED** [review]

**Comment by AmyHeiser** [comment]
Review of release/testing: 
@GiaJordan I had [FDS-1046](https://sagebionetworks.jira.com/browse/FDS-1046) prioritized for v23.12.1, and it has some similar and some different tests failing, so I updated that ticket rather than making a new one, but let me know if they make sense to separate.  
And we have a ticket to update GX to latest version FDS-123, so I'll move that one up as well to address the risks you mentioned above.  
Created a new ticket to address the deprecated NumPy warning. [FDS-1320](https://sagebionetworks.jira.com/browse/FDS-1320)
You also mentioned that a test plan needs to be updated to exclude the `rule_benchmark` marked tests in `test_api.py`, but I'm not the right person to handle that, are you asking for ticket or is that a quick update?

**Comment by GiaJordan** [comment]
> are you asking for ticket or is that a quick update

@AmyHeiser it's a quick update

**Comment by GiaJordan** [comment]
> I had [FDS-1046](https://sagebionetworks.jira.com/browse/FDS-1046) prioritized for v23.12.1, and it has some similar and some different tests failing, so I updated that ticket rather than making a new one, but let me know if they make sense to separate.
@AmyHeiser yes, please separate and not that this combination of failing tests was experienced with this rc

**Comment by mialy-defelice** [comment]
> > For this CLI test: `schematic manifest --config ~/path/to/config.yml get --dataset_id syn25614635 --data_type BulkRNA-seqAssay --sheet_url --use_annotations` The generated link and the example's columns were in a different order
> 
> I'll defer to @linglp and @mialy-defelice on severity

I don't think this matters bc they are out of schema columns pulled from annotations, so they have no defined order.

**Pull request merged**
