### PR TITLE
Format annotations consistently when populating an empty manifest

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
This PR aims at addressing the issue described in #459. Briefly, @allaway obtains `True`/`False` for a given Synapse annotation whereas I get `TRUE`/`FALSE` (the expected values) for the same annotation when pre-populating an empty manifest with annotation values. Of note, @allaway used the batch method since he has edit-access to the dataset whereas I used the non-batch method because I don't have edit-access. 

Note that this branch is builds upon @sujaypatil96's `develop-apply-black` branch (#452), where the codebase was formatted using `black`. The number of files changed in this PR will drop once #452 is merged. 

## Summary

- I created a test case to reproduce @allaway's behavior. 
  - Indeed, after creating a text (not boolean) annotation with the value `TRUE`, the fileview-based (_i.e._ batch) method returns `True` whereas direct API retrieval (_i.e._ non-batch) method returns `TRUE`. 
  - Until I update the code to handle this edge case, the tests will fail in this PR. 
- I updated the required version for `synapseclient` to 2.4

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
IIRC, this PR is just waiting on `synapseclient` v2.4 to be released, which will include a fix for the boolean formatting. This PR will pin the required version of the Synapse client to at least `2.4` and add the tests to cover this edge case.

**Comment by BrunoGrandePhD** [comment]
The test case that I added in this PR passes with the `synapseclient` pre-release of version 2.4. Once the release is done, I'll pin the version in this PR. 

```
❯ pip show synapseclient
Name: synapseclient
Version: 2.3.1

❯ poetry run pytest -k test_getDatasetAnnotations
tests/test_store.py::TestSynapseStorage::test_getDatasetAnnotations[batch] FAILED
tests/test_store.py::TestSynapseStorage::test_getDatasetAnnotations[non_batch] PASSED

❯ pip3 install --upgrade --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple synapseclient 
Successfully installed synapseclient-2.4.0.483

❯ pip show synapseclient
Name: synapseclient
Version: 2.4.0.483

❯ poetry run pytest -k test_getDatasetAnnotations                                                                                                                                                   
tests/test_store.py::TestSynapseStorage::test_getDatasetAnnotations[batch] PASSED
tests/test_store.py::TestSynapseStorage::test_getDatasetAnnotations[non_batch] PASSED
```

**Comment by BrunoGrandePhD** [comment]
@sujaypatil96: I recall you hesitating to upgrade the requirement for `synapseclient` to 2.4. Could you remind me why?

**Comment by sujaypatil96** [comment]
@BrunoGrandePhD: Hm, I don't think it was `synapseclient==2.4`. We were hesitant about upgrading to `2.3` because of the lack of support for OAuth on the Data Curator App. I'm using `2.4` in my virtual environment at the moment and everything seems to be working fine.

**Review by milen-sage — APPROVED** [review]
Looks good! Sorry for the delay in reviewing, it slipped through the cracks.

**Pull request merged**
