### PR TITLE
Do not index attribute visualization dataframe when converting to `csv` for component viz endpoint

### PR DESCRIPTION
**Pull request by GiaJordan**
Addresses [FDS-145](https://sagebionetworks.jira.com/browse/FDS-145)
Removes extra column found in data frame for attribute visualization.

Old format: (8 column headers and 9 columns)
```
,Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component
Sample ID,Sample ID,SampleID,TBD,True,,,,Biospecimen
Component,Component,Component,TBD,False,,,,Biospecimen
Tissue Status,Tissue Status,TissueStatus,TBD,True,,"['Healthy', 'Malignant']",,Biospecimen
Patient ID,Patient ID,PatientID,TBD,True,,,,Biospecimen
Component,Component,Component,TBD,False,,,,Patient
Patient ID,Patient ID,PatientID,TBD,True,,,,Patient
Diagnosis,Diagnosis,Diagnosis,TBD,True,,"['Healthy', 'Cancer']",,Patient
Sex,Sex,Sex,TBD,True,,"['Female', 'Other', 'Male']",,Patient
Year of Birth,Year of Birth,YearofBirth,TBD,False,,,,Patient
Family History,Family History,FamilyHistory,TBD,False,True,," If Diagnosis is ""Cancer"" then ""Family History"" is required",Patient
Cancer Type,Cancer Type,CancerType,TBD,False,True,"['Colorectal', 'Prostate', 'Lung', 'Breast', 'Skin', '']"," If Diagnosis is ""Cancer"" then ""Cancer Type"" is required",Patient
Sample ID,Sample ID,SampleID,TBD,True,,,,BulkRNA-seqAssay
Component,Component,Component,TBD,False,,,,BulkRNA-seqAssay
Filename,Filename,Filename,TBD,True,,,,BulkRNA-seqAssay
File Format,File Format,FileFormat,TBD,True,,"['CSV/TSV', 'FASTQ', 'BAM', 'CRAM']",,BulkRNA-seqAssay
Genome Build,Genome Build,GenomeBuild,TBD,False,True,"['GRCh37', 'GRCm39', 'GRCh38', 'GRCm38', '']"," If File Format is ""CSV/TSV"" OR ""BAM"" OR ""CRAM"" then ""Genome Build"" is required",BulkRNA-seqAssay
Genome FASTA,Genome FASTA,GenomeFASTA,TBD,False,True,," If File Format is ""CRAM"" then ""Genome FASTA"" is required",BulkRNA-seqAssay
```

New Format: (8 column headers and 8 columns)
```
Attribute,Label,Description,Required,Cond_Req,Valid Values,Conditional Requirements,Component
Patient ID,PatientID,TBD,True,,,,Biospecimen
Tissue Status,TissueStatus,TBD,True,,"['Malignant', 'Healthy']",,Biospecimen
Sample ID,SampleID,TBD,True,,,,Biospecimen
Component,Component,TBD,False,,,,Biospecimen
Sex,Sex,TBD,True,,"['Other', 'Male', 'Female']",,Patient
Component,Component,TBD,False,,,,Patient
Year of Birth,YearofBirth,TBD,False,,,,Patient
Patient ID,PatientID,TBD,True,,,,Patient
Diagnosis,Diagnosis,TBD,True,,"['Cancer', 'Healthy']",,Patient
Family History,FamilyHistory,TBD,False,True,," If Diagnosis is ""Cancer"" then ""Family History"" is required",Patient
Cancer Type,CancerType,TBD,False,True,"['Lung', 'Colorectal', 'Prostate', 'Breast', 'Skin', '']"," If Diagnosis is ""Cancer"" then ""Cancer Type"" is required",Patient
File Format,FileFormat,TBD,True,,"['FASTQ', 'CSV/TSV', 'CRAM', 'BAM']",,BulkRNA-seqAssay
Filename,Filename,TBD,True,,,,BulkRNA-seqAssay
Sample ID,SampleID,TBD,True,,,,BulkRNA-seqAssay
Component,Component,TBD,False,,,,BulkRNA-seqAssay
Genome Build,GenomeBuild,TBD,False,True,"['GRCm39', 'GRCm38', 'GRCh37', 'GRCh38', '']"," If File Format is ""CSV/TSV"" OR ""CRAM"" OR ""BAM"" then ""Genome Build"" is required",BulkRNA-seqAssay
Genome FASTA,GenomeFASTA,TBD,False,True,," If File Format is ""CRAM"" then ""Genome FASTA"" is required",BulkRNA-seqAssay
```

[FDS-145]: https://sagebionetworks.jira.com/browse/FDS-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by linglp** [comment]
@GiaJordan @mialy-defelice there seems to be an error in HTAN schema [here](https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld), that when I used `/visualize/attribute` endpoint, I got an error: 

```
Traceback (most recent call last):
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/connexion/decorators/produces.py", line 41, in wrapper
    response = function(request)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
  File "/Users/lpeng/Library/Caches/pypoetry/virtualenvs/schematicpy-9OomxyhV-py3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic_api/api/routes.py", line 578, in get_viz_attributes_explorer
    attributes_csv = AttributesExplorer(temp_path_to_jsonld).parse_attributes(save_file=False)
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/visualization/attributes_explorer.py", line 77, in parse_attributes
    json_schema = self.sg.get_json_schema_requirements(
  File "/Users/lpeng/Documents/schematic-git2/schematic/schematic/schemas/generator.py", line 488, in get_json_schema_requirements
    raise ValueError(f"'{source_node}' is not a valid component in the schema.")
ValueError: 'File' is not a valid component in the schema.
```
With source node "File", and `self.requires_dependency_relationship=requiresDependency`, the following code returns empty: 
```
        root_dependencies = self.get_adjacent_nodes_by_relationship(
            source_node, self.requires_dependency_relationship
        )
```

**Review by lakikowolfe — APPROVED** [review]
This is working for me. The returned content looks good for DFA's purposes. Thanks Gia!

**Review by mialy-defelice — CHANGES_REQUESTED** [review]
I would prefer a flag to allow drop the extra column or not. 

This attributes explorer is now being used for two different platforms (the schema viz tool and the DFA), so we need to make sure we accommodate the schema viz tool and don't break it.

**Comment by linglp** [comment]
> I would prefer a flag to allow drop the extra column or not.
> 
> This attributes explorer is now being used for two different platforms (the schema viz tool and the DFA), so we need to make sure we accommodate the schema viz tool and don't break it.

That sounds like a good idea Mialy. Thanks for noting it.

**Comment by GiaJordan** [comment]
Thanks for your review @mialy-defelice @linglp @lakikowolfe,  I'll add the flag to control the behavior

**Review by mialy-defelice — APPROVED** [review]
Looks great Gianna!

**Pull request merged**
