### PR TITLE
Develop an endpoint to return data types of columns in a manifest 

### PR DESCRIPTION
**Pull request by linglp**
This PR is related to the issue [here](https://github.com/Sage-Bionetworks/schematic/issues/807). Here are the tests that I did: 
- Test manifest [here](https://www.synapse.org/#!Synapse:syn32602107)
Output: 
```
{
  "Component": "string",
  "File Format": "string",
  "Filename": "string",
  "Genome Build": "string",
  "Genome FASTA": "string",
  "Sample ID": "Int64",
  "Test": "Float64",
  "Test2": "string",
  "Test3": "string",
  "Test4": "object",
  "Test5": "string",
  "entityId": "string"
}
```

- Test manifest [here](https://www.synapse.org/#!Synapse:syn32631266)
Output: 
```
{
  "Check Ages": "Int64",
  "Check Float": "Float64",
  "Check Int": "Float64",
  "Check List": "string",
  "Check Match Exactly": "Int64",
  "Check Match at Least": "Int64",
  "Check Num": "object",
  "Check Range": "Int64",
  "Check Recommended": "string",
  "Check Regex List": "string",
  "Check Regex Single": "string",
  "Check String": "object",
  "Check URL": "string",
  "Check Unique": "string",
  "Component": "string"
}
```

Notes: if two rows under the same column have different data types (i.e. an integer and a string), then it will return as type `object`. Currently, there's also no type `list`. `list` like object (see test 1, column `Test 2` and `Check Regex List` column in test 2)  get returned as "string"

### CODE REVIEW

**Comment by linglp** [comment]
@GiaJordan Just like we discussed in Slack, if I do not add `org_df = org_df.astype(str)` in `load_df` function, I would get error: `TypeError: descriptor 'isdigit' for 'str' objects doesn't apply to a 'float' object`. Could you check if I could do that? I am not sure if that would affect anything downstream. Thanks

**Comment by linglp** [comment]
@ychae this one is almost done. I am just waiting for Gianna come back and double check a line of code.

**Comment by GiaJordan** [comment]
@linglp it seems like the line you added is changing the behavior of cell values left empty and filling them in with something, and that's what's causing the `Check Recommended` assertion in the tests to fail

**Comment by linglp** [comment]
> @linglp it seems like the line you added is changing the behavior of cell values left empty and filling them in with something, and that's what's causing the `Check Recommended` assertion in the tests to fail

Thank you for the hint! I have figured out how to resolve the error in testing :0

**Review by milen-sage — APPROVED** [review]

**Pull request merged**
