### PR TITLE
Add timing of validation operations to DEBUG log

### PR DESCRIPTION
**Pull request by GiaJordan**
Add timing information to the `DEBUG` message level for:

- Manifest ingress 
- GE validation 
- In-House validation 
    - Cross manifest rule validation 
    - cross manifest rule manifest collection 
- JSON Schema validation 
- Total validation time (from command line)

requires merge of #1180

For `Invalid_test_manifest.csv` on a 4 Core 16Gb ram Windows 10 machine, performance was:
```
debug: GE Elapsed time 20.02935370002524
debug: Rule list strict elapsed time: 0.010837499983608723
debug: Rule list strict elapsed time: 0.004154199996264651
debug: Rule regex match [a-f] elapsed time: 0.003557899995939806
debug: Rule regex match [a-f] elapsed time: 0.006869399978313595
debug: Rule regex search [a-f] elapsed time: 0.0024847000022418797
debug: Rule url elapsed time: 1.1424103999743238
**debug: Cross manifest gathering elapsed time 10.97326199998497**
debug: cross manifest validation time 0.2818167000077665
debug: Rule matchAtLeastOne Patient.PatientID set elapsed time: 11.257951300009154
**debug: Cross manifest gathering elapsed time 10.789340899995295**
debug: cross manifest validation time 0.5386755999934394
debug: Rule matchAtLeastOne MockComponent.checkMatchatLeastvalues value elapsed time: 11.33193260000553
**debug: Cross manifest gathering elapsed time 10.50449920000392**
debug: cross manifest validation time 0.5352578000165522
debug: Rule matchExactlyOne MockComponent.checkMatchExactly set elapsed time: 11.044897100015078
**debug: Cross manifest gathering elapsed time 10.716369999980088**
debug: cross manifest validation time 0.5694077000080142
debug: Rule matchExactlyOne MockComponent.checkMatchExactlyvalues value elapsed time: 11.293306500010658
debug: In House validation elapsed time 46.35183119997964
debug: JSON Schema validation elapsed time 0.05784150000545196
debug: Total elapsed time 66.62552810000489 seconds
```
9 Expectations were included in the expectation suite. For individual rules, cross manifest validation takes the longest, with the bottleneck being the gathering of manifests to validate against.

Benchmarking with large manifests will occur in #1184

### CODE REVIEW

**Review by mialy-defelice — CHANGES_REQUESTED** [review]
This is great Gianna!

Its working for me as expected.
I noticed a typo, for `Load Eplased time` in `df_utils.py` lines 34 and 56.

**Review by mialy-defelice — APPROVED** [review]
Looks good!

**Comment by GiaJordan** [comment]
> Looks good!

Thank you! @mialy-defelice

**Comment by linglp** [comment]
@GiaJordan I am curious how could I test out the code here. I tried changing the code here to "DEBUG" but I can't find the elapsed time part in my log: 
```
logging.basicConfig(
    filename='myapp.log',
    format=("%(levelname)s: [%(asctime)s] %(name)s" " - %(message)s"),
    #level=logging.WARNING,
    level=logging.DEBUG,
    datefmt="%Y-%m-%d %H:%M:%S",
)
```
Is there something else that I would need to change? I am also curious if we should provide functionalities of setting log level ("DEBUG", "INFO", or "WARNING") by using CLI..

**Comment by GiaJordan** [comment]
Hey @linglp, #1180 actually just provided the functionality to set the logger from the command line for schematic and its submodules. I'm not sure if setting the level from the config like you're doing would cause the level to apply to all the submodules or not. Could you try from the CLI?

**Comment by linglp** [comment]
Just want to note here that: `schematic model --config config.yml validate --manifest_path /path/to/Invalid_Test_Manifest.csv  --data_type MockComponent --verbosity DEBUG` could reproduce the timing result

**Pull request merged**
