### PR TITLE
Update `synapseClient` dependency and api for manifest table uploads

### PR DESCRIPTION
**Pull request by GiaJordan**
Update minimum required version of the synapse python client to `v2.7.0` for permanent fix to #870, revert temporary solve introduced in #902

### CODE REVIEW

**Comment by linglp** [comment]
@GiaJordan this one should be good to go after merging #1115

**Review by linglp — APPROVED** [review]

**Comment by mialy-defelice** [comment]
@GiaJordan  Before push, lets make sure we have completed user testing, its on my list to do today.

**Review by mialy-defelice — APPROVED** [review]
Did user testing and it looks good!

**Comment by GiaJordan** [comment]
@mialy-defelice Thank you!

**Comment by linglp** [comment]
Note: I ran all the api tests after merging #1115 . All the tests were passed except: 
```
FAILED tests/test_api.py::TestManifestOperation::test_submit_manifest[upsert-None] - assert 500 == 200
FAILED tests/test_api.py::TestManifestOperation::test_submit_manifest[upsert-[{ "Patient ID": 123, "Sex": "Female", "Year of Birth": "", "Diagnosis": "Healthy", "Component": "Patient", "Cancer Type": "Breast", "Family History": "Breast, Lung", }]] - assert 500 == 200
```
That makes sense for now because we don't have the upsert functionality in this branch. The issue should be fixed in `develop` after merging #1081

**Pull request merged**
