### PR TITLE
Remove `try: catch:` block from manifest submission command function

### PR DESCRIPTION
**Pull request by GiaJordan**
Remove `try: catch:` block in `commands.submit_manifest` and verify that errors are handled elsewhere in the codebase at the appropriate function.

### CODE REVIEW

**Comment by GiaJordan** [comment]
@afwillia I wanted to check with you on the format of one of the errors raised and how it interacts with the DCA. The `ValidationError` that gets raised when there are validation errors in the manifest has a message but also includes the complete list of errors, in their individual list forms. This is an example message for one error in the manifest being validated:
```
Manifest could not be validated under provided data model. Validation failed with the following errors: [[2, 'MockRDB_id', 'On row 2 the attribute MockRDB_id does not contain the proper value type int.', 'str']
```
In cases with many errors, this could overwhelm users who get it depending on how the error is displayed. I'm not sure currently how this error is displayed DCA, but if it's necessary I can remove the error list from the error raised for the submission method.

**Comment by afwillia** [comment]
@GiaJordan DCA will show each error on a new line but if it's problematic we can limit the number of errors it shows. This seems okay to me. Thanks for checking.

**Comment by GiaJordan** [comment]
@afwillia perfect. Thanks for reviewing!

**Review by mialy-defelice — APPROVED** [review]
Looks great!

**Pull request merged**
