### PR TITLE
Installed schematic in docker file

### PR DESCRIPTION
**Pull request by linglp**
## Changelog
Added a line to install schematic in Dockerfile

Related to: [FDS-497 Install schematic in Dockerfile](https://sagebionetworks.jira.com/browse/FDS-497?atlOrigin=eyJpIjoiZTY2MTZkZjIwZWYxNDI0Yjg4MWExN2U3ZTI2NDI0NjQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

## To test this PR
1. docker build -t schematic-external .
2. Launch docker container based on the docker image that just built 
3. install vim inside the container: `apt install vim`
4. run `vim .synapseConfig` and copy and paste your content of `.synapseConfig`
5. run a schematic cli command: `schematic init --config config.yml`
which proves that schematic cli is working as expected

### CODE REVIEW

**Comment by GiaJordan** [comment]
Adding comment to reflect earlier discussion on slack:
Having issued testing. Cannot move from step 2 to 3, container immediately exits (both from CLI and GUI) and I can't enter any commands. Also I haven't been able to perform steps 2 and 3 at the same time successfully

**Comment by linglp** [comment]
> Adding comment to reflect earlier discussion on slack: Having issued testing. Cannot move from step 2 to 3, container immediately exits (both from CLI and GUI) and I can't enter any commands. Also I haven't been able to perform steps 2 and 3 at the same time successfully

Very strange. I tried again and could not reproduce the error that you are seeing. For me, the container works: 
Screen Shot 2023-06-02 at 7 02 36 PM

and I could interact with the container after clicking on the "CLI" logo...

When I do `docker ps`, i could see: 
```
(schematicpy-9OomxyhV-py3.9) lpeng@w153 schematic % docker ps
CONTAINER ID   IMAGE                       COMMAND     CREATED         STATUS         PORTS     NAMES
7de3e7915716   schematic-external:latest   "python3"   3 minutes ago   Up 3 minutes             reverent_lovelace
```

But maybe you could try the command: `docker run -i -t schematic-external:latest /bin/bash` instead of using the ui. This command also works for me, and then you could work on step 3

**Comment by GiaJordan** [comment]
thanks @linglp, I was able to progress to step 5. Running that command though yields `bash: schematic: command not found`

**Comment by linglp** [comment]
@GiaJordan that's so strange. I could see schematic starting though.... 

Screen Shot 2023-06-02 at 10 53 51 PM

**Review by andrewelamb — APPROVED** [review]

**Comment by linglp** [comment]
@andrewelamb thank you for checking!

**Pull request merged**
