### PR TITLE
Reorganize validation message level determination as a precursor to single rule disjunction 

### PR DESCRIPTION
**Pull request by GiaJordan**
This PR will help enable single rule disjunction by reworking how validation message levels are determined and the `IsNA` rule modifier introduced in #1200. The error/warning/no-message determination logic of all validation rules has been reworked to be compatible with this new rule modifier and has been simplified to be easier to maintain.

Rule compatibility with the `IsNA` modifier will be finished in a subsequent PR.

### CODE REVIEW

**Comment by GiaJordan** [comment]
@mialy-defelice resolving the conflicts was trivial; this is ready to be reviewed

**Comment by mialy-defelice** [comment]
@GiaJordan I see how to the functions were refactored for simplicity, but I am having trouble following how this enables single rule disjunction? Can you explain this again?

**Comment by GiaJordan** [comment]
@mialy-defelice single rule disjunction will be enabled with #1369 
I separated the refactor from the feature addition for better organization and ease of review

**Comment by mialy-defelice** [comment]
@GiaJordan I guess my question came from this part of the description:
``` 
 The error/warning/no-message determination logic of all validation rules has been reworked to be compatible with this new rule modifier
```
How do these changes allow compatibility?

**Comment by GiaJordan** [comment]
> How do these changes allow compatibility?

@mialy-defelice When the `IsNA` rule was introduced, it was introduced [only for the type checking rules ](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/models/validate_attribute.py#L258)because it was specific to @/andrewelamb's use case then.

The logic for `IsNA` [now is in](https://github.com/Sage-Bionetworks/schematic/blob/develop-val-error-handling-FDS-1352/schematic/models/validate_attribute.py#L434) `get_message_level()` which is used by all of the rules when determining which level of message to raise.

**Comment by mialy-defelice** [comment]
Ah gotcha, I understand now, thanks!

**Comment by GiaJordan** [comment]
@mialy-defelice no problem!

**Review by mialy-defelice — APPROVED** [review]

**Comment by mialy-defelice** [comment]
Pushing up to dev, then will merge single rule disjunction directly to dev.

**Pull request merged**
