### PR TITLE
Schematic codebase formatted using black

### PR DESCRIPTION
**Pull request by sujaypatil96**
I ran this command to auto-format all the Python files within the `schematic` codebase (including all sub-directories):

`black schematic`

I also modified the `pyproject.toml` file to add a section on `[tool.black]` configuration.

For next steps, should we add a `.flake8` file and enforce linting with Flake8? Like @BrunoGrandePhD mentioned we can start using pre-commit to run Black and Flake8 hooks.

CC: @BrunoGrandePhD and @milen-sage

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@sujaypatil96: Can you put the configuration changes in a separate PR? As for the pre-commit hooks (which you can include in that separate PR as well), this looks relevant:

https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by sujaypatil96** [comment]
Yup, I was looking at the same article. Thanks @BrunoGrandePhD.

I've removed the configuration commits. I'll create a separate PR for them. I think this is ready for review now.

**Comment by BrunoGrandePhD** [comment]
@sujaypatil96: I think it makes more sense to review and merge the `black` and `flake8` configuration first and then apply it to the files in this PR. Then, we can "review" and merge this PR. By review, I'm just referring to confirming that everything works as expected. So far, the tests all seem to pass, but it would be good to confirm that the tests that are skipped on GitHub work locally. I can do this, but I want us to agree on the configuration first.

**Comment by BrunoGrandePhD** [comment]
@sujaypatil96: You requested a review after I posted my previous comment. Did you miss it?

**Comment by sujaypatil96** [comment]
Oh, sorry, my apologies @BrunoGrandePhD. I missed your comment. I didn't see your comment about getting the `black` and `flake8` configuration files in first. I'll open a draft PR for that in a while, and requests for comments on that, and then we can come back to this.

**Comment by sujaypatil96** [comment]
I think this PR is ready for review @BrunoGrandePhD. The entire codebase has been `black` formatted.

**Comment by BrunoGrandePhD** [comment]
@sujaypatil96: Can you paste (or link to) an example?

**Comment by sujaypatil96** [comment]
Oh right, my bad. Here's a [line](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py#L92) of code from the `schematic.schemas.explorer` module. You can see how `black` formats the whole [file](https://github.com/Sage-Bionetworks/schematic/blob/develop/schematic/schemas/explorer.py).

**Comment by sujaypatil96** [comment]
I learned that comments are not handled by black, so you can ignore my above comment.

Reference: https://github.com/psf/black/issues/208

**Review by BrunoGrandePhD — APPROVED** [review]
Given that black should only be making formatting changes (_i.e._ changes that don't affect functionality) and all tests still pass, I'm happy to merge this PR. I'm not going to comb through every change black introduced in this PR. 

We should follow up with another PR to address the flake8 linting errors (_e.g._ long comments and docstrings). @sujaypatil96: Are you interested in taking that on since you've been reading about this?

**Comment by sujaypatil96** [comment]
Thanks @BrunoGrandePhD, makes sense. Let's get this PR in.

Yup, I'll take up the task of reducing the flake8 linter warnings. I'll create an issue for that and address it in a separate PR. Merging this PR now.

**Review by BrunoGrandePhD — COMMENTED** [review]
@milen-sage: As per our code review yesterday, I just went through all 35 files to look for any diffs (especially deletions) that aren't just formatting changes. I didn't spot any.

**Comment by milen-sage** [comment]
Same^ :)

**Pull request merged**
