### PR TITLE
Support listing all files in a dataset independent of folder hierarchy in the dataset

### PR DESCRIPTION
**Pull request by milen-sage**
getFilesInStorageDataset now returns all files w/in a specified dataset independent of dataset folder hierarchy;

Added additional optional argument 'fullpath' to the method.

If fullpath is set to True (default) the function includes the full path to the file (relative to the dataset folder) as part of the filename. Otherwise, if fullpath is set to False, the filename contains the base filename.

No modifications should be needed to the data curator app.

### CODE REVIEW

**Comment by allaway** [comment]
Hey, I just noticed this pr come through on the slack channel. Am I correct in understanding that given a folder ID, this will retrieve all files within just that ID as well as all subfolders (ie. recursively)? 

If so,  I think this will close https://github.com/nf-osi/NF_data_curator/issues/8

**Comment by milen-sage** [comment]
Yes - this is correct.

**Comment by allaway** [comment]
That's awesome. Thanks!

**Comment by allaway** [comment]
(as an aside, we've generalized the frontend to list all folders within the selected project, so with these two changes, a user should be able to scope their manifest exactly as they'd like, let me know if this is a change you'd like me to push back upstream)

**Comment by milen-sage** [comment]
oh cool! Yes, please push the project-based scoping back to schematic (especially after you've tested the folder hierarchy bit with it)  and we'll incorporate in the main backend.

**Comment by milen-sage** [comment]
@xdoan - I wonder if some of the fixes in this PR will address what Dave Gibbs was experiencing here https://github.com/sage-bionetworks/htan-coordination/issues/194? I assume that hasn't been deployed in the test app he was using yet?

**Comment by xdoan** [comment]
it shouldn't be related but am testing it now

**Comment by xdoan** [comment]
am getting an empty list returned from `syn_store$getFilesInStorageDataset(synStore_obj, folder_synID)` in R and do not see an example scripts that run this function in python to check output/ input variables. Please share test scripts used @milen-sage

**Comment by milen-sage** [comment]
https://github.com/Sage-Bionetworks/schematic/blob/main/schematic/synapse/examples/store_usage.py#L36

might want to change the folder synid^ (to check subfolder hierarchy); I've tested with syn22493888 and syn22727193

**Comment by xdoan** [comment]
works on python, not working on R on server. Did anything change that would affect reticulate's ability to go from python to R? 

```
> syn_store$getFilesInStorageDataset(synStore_obj, "syn21999329") ### flat folder
[[1]]
[[1]][[1]]
[1] "syn21999337"

[[1]][[2]]
[1] "sample_file2.img"


[[2]]
[[2]][[1]]
[1] "syn21999338"

[[2]][[2]]
[1] "sample_file3.img"


> syn_store$getFilesInStorageDataset(synStore_obj, "syn22493888") ### nested folder
list()
```

**Comment by milen-sage** [comment]
With or w/o hierarchy the method returns a list of tuples:

- w/o hierarchy, project syn22727193: 
[('syn22727245', 'testing1/doc.txt'), ('syn22727298', 'testing1/doc1.txt')]

- w/ hierarchy, project syn22493888:     
[('syn22727245', 'entityTest/counts/testing1/doc.txt'), ('syn22727298', 'entityTest/counts/testing1/doc1.txt'), ('syn22989988', 'entityTest/not_counts/file1.txt'), ('syn22989990', 'entityTest/not_counts/file2.txt')] 

I believe this was the output format expected from this method before the change as well.

**Comment by milen-sage** [comment]
ok @xdoan  you're correct it's not been merged yet :)
so I guess the issue with disconnect #305 is not due to this file listing?

**Comment by xdoan** [comment]
have to be careful to set up subfolder hierarchy before adding new subfolders if you've uploaded a manifest in a subfolder already. 

Seems to work for other schemas, but scRNAseq Level 1 is not working. 
scRNAseq Level 2 with full paths:
https://docs.google.com/spreadsheets/d/1piAEiFi5OCuUyTGdTLNUP_wOKzRFHThaDx6qRba-eMc/edit#gid=0

error on scRNAseq Level 1:
```
Warning: Error in py_call_impl: IndexError: pop from empty list

Detailed traceback: 
  File "/home/xdoan/ShinyApps/HTAN_Shiny_dev/schematic/schematic/models/metadata.py", line 133, in getModelManifest
    return mg.get_manifest()
  File "/home/xdoan/ShinyApps/HTAN_Shiny_dev/schematic/schematic/manifest/generator.py", line 215, in get_manifest
    json_schema = self.sg.get_json_schema_requirements(self.root, self.title)
  File "/home/xdoan/ShinyApps/HTAN_Shiny_dev/schematic/schematic/schemas/generator.py", line 489, in get_json_schema_requirements
    process_node = nodes_to_process.pop(0)

  76: <Anonymous>
```
on the backend are you able to generate a scRNAseq Lvl 1 schema? I am testing specifically on milen-sage-develop-file-hierarchy which does not have the recent biospec merge

**Review by xdoan — APPROVED** [review]

**Comment by milen-sage** [comment]
Great! 

True - we currently assume one manifest per dataset (which makes sense to me, but if we/you/others see different usecases we can support them). We assume the manifest is placed in the dataset root folder; so at present, if there is an existing manifest in a subfolder that's not expected behavior.

**Pull request merged**
