### PR TITLE
Changes to schema reflecting clinical data updates and date-related field changes

### PR DESCRIPTION
**Pull request by milen-sage**
@xdoan this should only require changing the schema names for clinical data tier 3 to 

LungCancerTier3
ColorectalCancerTier3
BreastCancerTier3
BrainCancerTier3
AcuteLymphoblasticLeukemiaTier3
OvarianCancerTier3
ProstateCancerTier3
SarcomaTier3
PancreaticCancerTier3
MelanomaTier3

### CODE REVIEW

**Comment by xdoan** [comment]
did you and Nithya already QC or are there things I should check?

**Comment by milen-sage** [comment]
Yes, I checked the clinical data related updates against the changes Nithya requested. We can go ahead with updating the schema (just making sure that the clinical tier 3 schema names^ are updated and the templates can be generated).

**Comment by nithyav21** [comment]
@xdoan - I have not reviewed any spreadsheets. Is this GH for the schema name change?

**Comment by milen-sage** [comment]
> @xdoan - I have not reviewed any spreadsheets. Is this GH for the schema name change?

@nithyav21 this addresses https://github.com/sage-bionetworks/htan-coordination/issues/90 and https://github.com/sage-bionetworks/htan-coordination/issues/123

**Comment by xdoan** [comment]
@milen-sage @nithyav21 this is live on the dev app https://www.synapse.org/#!Wiki:syn20930961/ENTITY and I would prefer our usual QC (Milen, me, Nithya) if possible before this goes public. We have previously found minor errors and unless there is a good reason to push the updates with a risk of errors, or there has been thorough QC done (template generation and validating and submitting) I would be wary of putting this on the prod server. 

Also the schema names were already what you described @milen-sage ? So not sure what you mean by changing them again unless there is a minor change I missed somehow.

**Comment by milen-sage** [comment]
Great - if schema names are the same, I must have changed them last time :)

**Comment by xdoan** [comment]
So testing stuff on the app atm: Things I found
- [Tier 1 Demographics](https://docs.google.com/spreadsheets/d/1kNFdOVKGFIUHL2339_AcqA2ZkNZjjhTFupIpuwKtBhE/edit#gid=0) 
don't see  ‘ country_of_residence_at_enrollment’ 
- [Tier 1 Exposure] (https://docs.google.com/spreadsheets/d/1PXGcVBRpjgdoxcjAKUb9RQX5hW-4SQUsB0pZ5rIGcVI/edit#gid=0)
I still see alcohol exposure?

I pulled the PR and restarted the dev app but somehow I'm not seeing all the changes, do I still have an old version I'm testing with?
```
schematic$ git pull https://github.com/milen-sage/schematic.git develop-schema-update
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 12 (delta 8), reused 12 (delta 8), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/milen-sage/schematic
 * branch            develop-schema-update -> FETCH_HEAD
Merge made by the 'recursive' strategy.
 data/csv/HTAN.csv                   |  1364 +-
 data/schema_org_schemas/HTAN.jsonld | 41157 +++++++++++++++++++++++++++++++++++-------------------------
 2 files changed, 24884 insertions(+), 17637 deletions(-)

(base) xdoan@ip-10-5-20-187:~/ShinyApps/HTAN_Shiny_dev$ touch restart.txt 
```

**Comment by milen-sage** [comment]
@xdoan thanks for the catch on country of residence; just added a commit on that.

Let's leave 'Alcohol Exposure' in; it's a field that they can specify 'Not Reported' if they don't have data (some do have data that they want to provide, based on prior conversations).

Wrt versions - you can take a look and see if you see country of residence; if yes, then you are on the new version.

**Comment by milen-sage** [comment]
Also, you can check Biospecimen; if you don't see 'Microscope' in it, then you are on the new version.

**Comment by nithyav21** [comment]
@milen-sage and @xdoan - Based on conversations with a few centers this extra field 'alcohol exposure' is causing confusion as this is not part of data dictionary and we have other alcohol related fields in the template. Looks like some centers have prepared data based on the dictionary and this extra field is throwing them off. Just some feedback based on my interactions with center reps.

**Comment by milen-sage** [comment]
From Karla Helvi - (email Fri Nov 6):
"The alcohol-related questions are missing from the template."

The Alcohol Exposure field is what triggers the addition of conditionally dependent alcohol-exposure related fields (i.e. if Alcohol Exposure data is reported) in the template.

There are a few changes between the data dictionary and the actual data model; let's leave the Alcohol Exposure field in. People can select 'Not Reported' if not applicable to them.

**Comment by nithyav21** [comment]
sure @milen-sage !

As long as we have the alcohol related questions Karla is asking for, that should be okay. These questions are
- alcohol history
- alcohol type
- alcohol intensity
- alcohol drinks per day
- alcohol days per week.

On Fri, Nov 6, 2020 at 11:04 AM Helvie, Karla E <KarlaE_Helvie@dfci.harvard.edu> wrote:
Hi Nithya and Milen,
I’ve also noticed a few other things:
Diagnosis:

The template seems to be missing several fields. I count 99 in the data dictionary and only 87 in the template; I didn’t do a complete comparison but noticed the “weiss_assessment_score” was one that was missing.

Exposure:

The alcohol-related questions are missing from the template.

Molecular Test:

No template available.
Thanks,

Karla

**Comment by xdoan** [comment]
Thanks for the edits!

- country_of_residence_at_enrollment

Could you add a description that it is at enrollment or put that in the name? Currently I see Country of Residence and people may have moved/etc. 

-  Alcohol Exposure 

Should a change just be made to the data dictionary then? It is also currently required and that might make people's schemas get errors more if they didn't expect it. I personally would cross ref between the spreadsheet and data dictionary if I wanted to be sure I was filling it out correctly so any discrepancies would confuse me, possibly meaning you and Nithya will probably continue to get questions about that. 

- Follow Up 

https://docs.google.com/spreadsheets/d/1VwnF9KBbkA3y6WtK1o1QGaEwzxT4hRD3FKjR04A7ZsE/edit#gid=0 still see Progression or Recurrence highlighted as "required"

**Comment by milen-sage** [comment]
Description for country of residence has been updated.

Alcohol Exposure 
- all related fields  Karla has suggested are already in the schema
- updating the dictionary wouldn't be my highest priority (though definitely beneficial to avoid confusion); see email exchange with  Lynne regarding relationship between RFC data dictionary and final data model; the confusion here stems from calling a data dictionary something that is a RFC artifact  and not a data dictionary associated with a data model version

Follow up - this fields serves similar purpose to Alcohol Exposure: if it's not applicable to people can select 'Not Reported'; this has been discussed before as well.

**Comment by xdoan** [comment]
In the interim before we get the official data standards up, I think updating the dictionary is medium priority bc it would reduce auxiliary emails/communications/questions. This would address the issue if people are programmatically filling out templates based on the dictionary and there is a discrepancy in fields and what is optional vs required. Its true ppl can just put in the required field as not reported, but they would "fail slower". 

In addition I think we need some better messaging to check for the most recent schema (generated via app or api) to fill out templates from and maybe we can bring that up in the Ops/Coordincation/SC call?

**Review by xdoan — APPROVED** [review]

**Comment by nithyav21** [comment]
I agree with @xdoan on - "possibly meaning you and Nithya will probably continue to get questions about that." 

We will have to come up with a communication/ process to centers if we are changing/adding things on the template (from the dictionary). Else, we are get bombarded with questions.

**Comment by milen-sage** [comment]
Yes, we are working on schema/data dictionary explorer that will be linked to the data portal.

Meanwhile, people can download templates directly from the data curator app (that is when the data curator is up... it looks like our server died). We can also post latest templates to github similarly to HTAN and HCA.

**Comment by xdoan** [comment]
What's the timeline on the data standards page? If its long enough it might be beneficial to decrease random emails and update the dictionary, if its not then it might not be too bad. 

I think we could use a big disclaimer on the RFC and spreadsheet that this is NOT the definite model and to go dl the latest template, people are much more familiar with the RFC process so default to that (as would I bc you have a click a lot). I wouldn't want to post templates as they change very often and its hard to maintain.

**Comment by milen-sage** [comment]
You can monitor here: https://github.com/sage-bionetworks/htan-coordination/issues/222

3-4 weeks in Jan 2021; expected first deployment in Feb.

**Pull request merged**
