### PR TITLE
Changes to sequencing assays adding read indicator for paired sequencing

### PR DESCRIPTION
**Pull request by milen-sage**
E.g. is a file read1 or read2.

Also, for all sequencing levels > 1 we don't need parent biospecimen ID, we required parent data file ID - that is fixed now - high priority for HTAN provenance.

### CODE REVIEW

**Comment by milen-sage** [comment]
No changes to the data curator app should be required.

**Comment by milen-sage** [comment]
Added minor changes to a couple of descriptions; this will address Lynne's concerns (have coordinated with Nithya on that).

Could you ping her when the PR is merged - might be helpful to test generation of the exposure and biospecimen templates, but other than that things should be good.

**Comment by xdoan** [comment]
Checked for the Parent Data File ID but not super clear on where the R1 R2 got changed but nothing broke so far!

**Review by xdoan — APPROVED** [review]

**Comment by xdoan** [comment]
@milen-sage Still see Shipping Type as required https://docs.google.com/spreadsheets/d/1aHQUJmedZ75lcRTVDT9nn2a7Tb8z8GpeipwDHlcJ8PE/edit#gid=0 in Biospec

**Comment by xdoan** [comment]
@nithyav21 would you be able to email Lynne and explain the updates?

**Comment by milen-sage** [comment]
> Checked for the Parent Data File ID but not super clear on where the R1 R2 got changed but nothing broke so far!
> 
> Checked Exposure and Biospec templates

Thanks, yes Read Indicator - R1 and R2 - were added based on Orr's comment in a recent meeting. If 'Library Layout' is paired end, we'd ask the user whether a given file is read 1 or 2. For scRNA-seq, the library layout is always paired end and at some point the attribute that indicates which file is R1 or R2 got dropped, so I added it back.

**Comment by nithyav21** [comment]
@xdoan and @milen-sage - Sure, I can email Lynne about the update.
One thing I observed in the Biospecimen Template is "Preservation Method" is not highlighted in blue. This should be required per
https://docs.google.com/spreadsheets/d/15mbfvYKpLTuSQO2M-bisCyoxTXoC3O-FYxA97hfk8Rg/edit?folder=1npGEclHXpCZ2Lz5yqzM2Ad4qQLwmtTUq#gid=1607346090
and
https://docs.google.com/spreadsheets/d/1uk3gces9xmdpEe5L6XMTp28dpBizsqfEQ6hVTPpralU/edit#gid=0

**Pull request merged**
