### PR TITLE
fix: install patch version of synapse python client 

### PR DESCRIPTION
**Pull request by linglp**
## Context
Related to: https://sagebionetworks.jira.com/browse/FDS-2197

## Main changes
* added test pypi as a source
* install synapseclient = "4.3.1"
* updated docker file to use poetry 1.7.1
* updated workflow files to use poetry 1.7.1

Note: without upgrading poetry version, I can't add test pypi as a source with key word "supplemental". For some reasons, our lock file is written by poetry version 1.7.1 but our workflow and docker file are using a lower version of poetry. I updated the poetry version to align with the version in lock file

## Test
Re-run profiler after launching the APIs in a docker container: 
```
INFO: [2024-07-10 19:12:27] manifest-submit - Monitoring manifest submission
INFO: [2024-07-10 19:13:04] httpx - HTTP Request: POST https://127.0.0.1/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-10 19:13:15] httpx - HTTP Request: POST https://127.0.0.1/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"

```

### CODE REVIEW

**Comment by linglp** [comment]
@GiaJordan @andrewelamb It is working on test PYPI. Let me update the code and point it to PYPI.

**Comment by andrewelamb** [comment]
@linglp I'll go ahead and approve, given the change you'll be making to use the pypi 4.3.1 version

**Review by andrewelamb — APPROVED** [review]

**Comment by linglp** [comment]
@GiaJordan @andrewelamb I ran into two `504` gateway time out when running manifest submission after spinning up schematic APIs locally in a docker container. I then ran manifest submission in a loop in profiler five times and they all returned 200. To be safe, I think I will spend some time and deploy it to aws-dev environment before merging.

**Comment by linglp** [comment]
@GiaJordan @andrewelamb After deploying to AWS, schematic profiler was automatically triggered, and I could see submission tests passed there. To make sure, I also ran schematic profiler locally five times for manifest submission and saw that all results were passing: 
```
venv) lpeng@w153 APITests % python3 manifest_submit.py
INFO: [2024-07-12 13:18:32] manifest-submit - Monitoring manifest submission
INFO: [2024-07-12 13:19:03] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:19:10] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:19:32] manifest-submit - Monitoring manifest submission
INFO: [2024-07-12 13:20:02] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:20:09] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:20:31] manifest-submit - Monitoring manifest submission
INFO: [2024-07-12 13:21:01] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:21:07] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:21:29] manifest-submit - Monitoring manifest submission
INFO: [2024-07-12 13:21:59] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:22:06] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:22:28] manifest-submit - Monitoring manifest submission
INFO: [2024-07-12 13:22:58] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=table_and_file "HTTP/1.1 200 OK"
INFO: [2024-07-12 13:23:04] httpx - HTTP Request: POST https://schematic-dev.api.sagebionetworks.org/v1/model/submit?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FSage-Bionetworks%2Fschematic%2Fdevelop%2Ftests%2Fdata%2Fexample.model.jsonld&dataset_id=syn51376664&asset_view=syn51376649&restrict_rules=True&use_schema_label=True&data_model_labels=class_label&table_manipulation=replace&manifest_record_type=file_only "HTTP/1.1 200 OK"
(venv) lpeng@w153 APITests % 
```

**Pull request merged**
