### PR TITLE
Develop excel export

### PR DESCRIPTION
**Pull request by milen-sage**
This addresses https://github.com/sage-bionetworks/htan_data_curator/issues/64

Feature requested by BU for entry of clinical data via excel, as well. 

No changes to data curator app required. High priority.
When on dev/prod app Nithya can test.

### CODE REVIEW

**Comment by milen-sage** [comment]
@xdoan not exactly sure why in addition to the commit that 
- adds support for cell border colors on google sheet manifest export to excel and open office; 
- reduces limit on dropdown items to 256 from 500 to accommodate the limit in excel
this PR is picking up changes related to PRs #301 and #299; those were merged in main a while back. All changes in this PR related to 299 and 301 seem correct; just surprised that these changes are not reflected in main already. Could you deploy and test?

**Comment by milen-sage** [comment]
@xdoan I just added a commit that restructured template generation avoiding limitations on number of items in a dropdown (formerly, 500 items in google sheet, ~256 in excel and openoffice). 

I tested on my end, it would be great if you could test on dev as well; no changes to the data curator app should be required:
- google sheet manifest generation should work as before (only effect: export to excel/openoffice should work better, which Nithya can confirm)
- file hierarchy walking, metadata submission, table updates on synapse should be working as before

**Review by xdoan — APPROVED** [review]

**Comment by xdoan** [comment]
in excel I see the border, but the comment color for the column is in red, is that expected for excel?

**Comment by xdoan** [comment]
@milen-sage in the imaging spreadsheet there isn't a dropdown for File Format with any values?

https://docs.google.com/spreadsheets/d/1IobNiGflM1driUToW2Da4OwBpKsc6sXPF5JQkwdg0G8/edit#gid=0

**Comment by milen-sage** [comment]
interesting I see the dropdown in the spreadsheets you linked^

**Comment by xdoan** [comment]
in excel do you see it?

**Pull request merged**
