### PR TITLE
v24.10.2

### PR DESCRIPTION
**Pull request by lakikowolfe**
[Release ticket](https://sagebionetworks.jira.com/browse/FDS-2503?focusedCommentId=223548&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-223548)

[Project scope](https://sagebionetworks.jira.com/projects/FDS/versions/34486/tab/release-report-all-issues)

### CODE REVIEW

**Comment by andrewelamb** [comment]
How is develop out-of-date with the main branch?

**Comment by lakikowolfe** [comment]
@andrewelamb are you asking me? I'm not sure

**Comment by andrewelamb** [comment]
Asking anyone :)

**Comment by lakikowolfe** [comment]
@andrewelamb should I wait on a response to update the branch?

**Comment by thomasyu888** [comment]
> Asking anyone :)

This happens sometimes when you make a PR into `main` from `develop`.  I've seen that sometimes you have to merge `main` back into `develop` for some reason...

**Comment by andrewelamb** [comment]
Thanks @thomasyu888 , @lakikowolfe if you could merge main into develop first that would be great. It looks like you can do it with the update branch button.

**Review by andrewelamb — APPROVED** [review]

**Comment by andrewelamb** [comment]
@lakikowolfe Go ahead and merge. The tests that are faailign all pass loccally for several individuals who've ran them.

**Comment by andrewelamb** [comment]
@lakikowolfe Hold for now @jaymedina Is trying the tests one mroe time, while nothing else is running

**Pull request merged**
