### PR TITLE
Save all properties that are Included in the domain of a Class

### PR DESCRIPTION
**Pull request by mialy-defelice**
Previously the way the JSONLD was constructed, if properties were in the domain of a Class only one property would be saved. This ignored other properties in the domain of that class, but also meant when doing the reverse lookup (all the classes that a property belongs to) would be incorrect. 

This addresses the specific case where the outputs of the API call `find_class_specific_properties` was outputting incorrect results when properties were in the domain of multiple classes.

This PR makes changes to the `df_parser.py` and `explorer.py` to correct this issue.

To work, user will need to recreate their JSON LD using:
```
 schematic schema convert path/to/test_model.model.csv 
```
then upload to GitHub and call API function.

### CODE REVIEW

**Comment by andrewelamb** [comment]
@mialy-defelice I'm testing with this branch and getting the error below with [this schema.csv](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.csv). I do not see this error in the current develop branch.


```
(schematicpy-gKAjXOOq-py3.9) (base) alamb@ALamb:~/repos/iAtlasSchema$ schematic -v DEBUG schema convert iatlas_schema.csv
WARNING: [2023-02-13 14:17:15] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

WARNING: [2023-02-13 14:17:15] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

WARNING: [2023-02-13 14:17:15] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

Starting schematic...
debug: Existing sub-commands need to be used with schematic.
debug: Schema definition csv ready for processing!
debug: Adding attributes
debug: Done adding attributes
debug: Adding and editing properties
Traceback (most recent call last):
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/bin/schematic", line 6, in <module>
    sys.exit(main())
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/alamb/repos/schematic/schematic/schemas/commands.py", line 56, in convert
    base_se = _convert_csv_to_data_model(schema_csv, base_schema)
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 786, in _convert_csv_to_data_model
    base_se = create_nx_schema_objects(rfc_df, base_se)
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 411, in create_nx_schema_objects
    property_info = se.explore_property(
  File "/home/alamb/repos/schematic/schematic/schemas/explorer.py", line 512, in explore_property
    property_info["domain"] = [self.uri2label(record["@id"]) for record in p_domain]
  File "/home/alamb/repos/schematic/schematic/schemas/explorer.py", line 512, in <listcomp>
    property_info["domain"] = [self.uri2label(record["@id"]) for record in p_domain]
TypeError: string indices must be integers
```

**Comment by mialy-defelice** [comment]
> @mialy-defelice I'm testing with this branch and getting the error below with [this schema.csv](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.csv). I do not see this error in the current develop branch.

It makes sense that you would get an error in this region in this branch but not develop. Is this the iatlas model you send me previously for testing? If not can you try that one and let me know if you're still getting an error?

**Comment by andrewelamb** [comment]
I tried an older [schema](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.csv) (I think this was the one I sent you), and it din't cause an error, but the jsonld didn't change at all. Is that expected?

**Comment by mialy-defelice** [comment]
> I tried an converting older csv [schema](https://github.com/CRI-iAtlas/iAtlasSchema/blob/develop/iatlas_schema.csv) (I think this was the one I sent you), and it din't cause an error, but the jsonld didn't change at all. Is that expected?

No, the JSONLD should change. It should end up looking like [this](https://github.com/mialy-defelice/data_models/blob/main/iatlas_schema.model.jsonld). What is the change you made that is different between both models?

**Comment by andrewelamb** [comment]
The one I'm getting the "string indices must be integers" has around 2x the number of Components and a alot of new attributes, compared to the older one.

**Comment by andrewelamb** [comment]
Do you know what's causing the "string indices must be integers"? I'm assuming it because I have validation rules such as 
"matchAtLeastOne nodes.id set error" and there is no "id" attribute in the nodes component?

**Comment by mialy-defelice** [comment]
> Do you know what's causing the "string indices must be integers"? I'm assuming it because I have validation rules such as
> "matchAtLeastOne nodes.id set error" and there is no "id" attribute in the nodes component?

No I haven't had time to investigate it yet, I'm working on the test failure right now. It shouldn't be doing any actual validation right now though. I suspect it could be something related to the error I'm currently exploring which is a list is getting unpacked in a way I wasn't expecting.

**Comment by andrewelamb** [comment]
@mialy-defelice I was mistaken it DID change the older schema:

**Comment by andrewelamb** [comment]
@mialy-defelice Yep, no errors this time!

I created a PR for the schema [here.](https://github.com/CRI-iAtlas/iAtlasSchema/pull/5/files#diff-ebc92d72ce4b5ca480ddd28186daa51720a062d4f06215437c8ff0825a206456)

(There have been some other changes made since please ignore those)

I did notice something weird. If you go to the bottom of the PR you'll see:
```

"rdfs:label": "CellimageNetwork",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:Network"


```

Become:

```

"rdfs:label": "CellimageNetwork",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:N"
                },
                {
                    "@id": "bts:E"
                },
                {
                    "@id": "bts:T"
                },
                {
                    "@id": "bts:W"
                },
                {
                    "@id": "bts:O"
                },
                {
                    "@id": "bts:R"
                },
                {
                    "@id": "bts:K"
                }
            ],
```

**Comment by mialy-defelice** [comment]
> I did notice something weird. If you go to the bottom of the PR you'll see:

Thanks for catching this! I'll investigate now.

**Comment by mialy-defelice** [comment]
@andrewelamb can you check now? Thanks for testing this so much!!

**Comment by andrewelamb** [comment]
@mialy-defelice  not a problem!

I'm seeing a new error:

```
(schematicpy-gKAjXOOq-py3.9) (base) alamb@ALamb:~/repos/iAtlasSchema$ schematic -v DEBUG schema convert iatlas_schema.csv
WARNING: [2023-02-15 10:48:53] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

WARNING: [2023-02-15 10:48:53] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

WARNING: [2023-02-15 10:48:53] py.warnings - /home/alamb/miniconda3/lib/python3.9/inspect.py:351: FutureWarning: pandas.UInt64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  value = getattr(object, key)

Starting schematic...
debug: Existing sub-commands need to be used with schematic.
debug: Schema definition csv ready for processing!
debug: Adding attributes
debug: Done adding attributes
debug: Adding and editing properties
debug: Done adding properties
debug: Component added to dependencies
debug: genes_id added to dependencies
debug: datasets_id added to dependencies
debug: genes_id added to dependencies
debug: snps_id added to dependencies
debug: features_id added to dependencies
debug: coloc_dataset_id added to dependencies
debug: qtl_type added to dependencies
debug: ecaviar_pp added to dependencies
debug: plot_type added to dependencies
debug: splice_loc added to dependencies
debug: tissue added to dependencies
debug: link added to dependencies
debug:  datasets added to dependencies
debug: Validation rules added
Traceback (most recent call last):
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/bin/schematic", line 6, in <module>
    sys.exit(main())
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alamb/.cache/pypoetry/virtualenvs/schematicpy-gKAjXOOq-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/alamb/repos/schematic/schematic/schemas/commands.py", line 56, in convert
    base_se = _convert_csv_to_data_model(schema_csv, base_schema)
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 785, in _convert_csv_to_data_model
    base_se = create_nx_schema_objects(rfc_df, base_se)
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 484, in create_nx_schema_objects
    new_class = get_class(
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 96, in get_class
    "rdfs:subClassOf": [
  File "/home/alamb/repos/schematic/schematic/schemas/df_parser.py", line 97, in <listcomp>
    {"@id": "bts:" + se.get_class_label_from_display_name(sub)}
  File "/home/alamb/repos/schematic/schematic/schemas/explorer.py", line 468, in get_class_label_from_display_name
    display_name = display_name.translate({ord(c): None for c in string.whitespace})
AttributeError: 'list' object has no attribute 'translate'
```

**Comment by mialy-defelice** [comment]
> @mialy-defelice not a problem!
> 
> I'm seeing a new error:


Okay @andrewelamb I think I have caught everything now... can you try one more (hopefully last) time?

**Comment by andrewelamb** [comment]
@mialy-defelice There error is gone, but I'm seeing this issue still:

```
"rdfs:label": "CellimageNetwork",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:N"
                },
                {
                    "@id": "bts:E"
                },
                {
                    "@id": "bts:T"
                },
                {
                    "@id": "bts:W"
                },
                {
                    "@id": "bts:O"
                },
                {
                    "@id": "bts:R"
                },
                {
                    "@id": "bts:K"
                }
            ],
```

**Comment by andrewelamb** [comment]
I'm only seeing the above issue with three attributes, is it possible something is wrong with the schema csv for those particular attributes?

**Comment by mialy-defelice** [comment]
> I'm only seeing the above issue with three attributes, is it possible something is wrong with the schema csv for those particular attributes?

This is what I see:
```
{
            "@id": "bts:CellimageNetwork",
            "@type": "rdfs:Class",
            "rdfs:comment": "TBD",
            "rdfs:label": "CellimageNetwork",
            "rdfs:subClassOf": [
                {
                    "@id": "bts:Network"
                }
```
I am unexpectedly seeing an issue pop up for a couple attributes in the dependsOn category so I'm going to test that too. 

Do you see:
```
 {
            "@id": "bts:patientId",
            "@type": "rdf:Property",
            "rdfs:comment": "TBD",
            "rdfs:label": "patientId",
            "schema:domainIncludes": [
                {
                    "@id": "bts:S"
                },
                {
                    "@id": "bts:L"
                },
                {
                    "@id": "bts:I"
                },
                {
                    "@id": "bts:D"
                },
                {
                    "@id": "bts:E"
                },
                {
                    "@id": "bts:S"
                }
            ],
```
?

**Comment by andrewelamb** [comment]
Yep, there were three of them, where that was occuring. What all three had in common where that they were components where the DependsOn and Properties columns listed attributes that weren't in the schema (because of typos). After I fixed all three that issue is now gone.

**Comment by andrewelamb** [comment]
> I see now it might be because you put things in the DependsOn and Properties columns that aren't listed as Attributes... I don't this this should be allowed? Let me investigate this more.

Looks like you found the same thing!

**Comment by mialy-defelice** [comment]
> Yep, there were three of them, where that was occuring. What all three had in common where that they were components where the DependsOn and Properties columns listed attributes that weren't in the schema (because of typos). After I fixed all three that issue is now gone.

So to confirm, everything looks as expected now? We can put this type of check in the refactor...we are putting in a module to look for consistency within a model.

**Comment by andrewelamb** [comment]
I think so! I'm just checking my most recent schema version and I'm not seeing any of that behavior after fixing a couple of those mismatches.

**Comment by andrewelamb** [comment]
@mialy-defelice The find_class_specific_properties endpoint is now returning all the attributes I was expecting as well.

**Review by andrewelamb — APPROVED** [review]

**Pull request merged**
