### PR TITLE
HTAN schema update

### PR DESCRIPTION
**Pull request by milen-sage**
Updated HTAN schema with biospecimen and minimal metadata for an assay not covered in RFCs.

### CODE REVIEW

**Comment by milen-sage** [comment]
Process: merge PR in develop when approved; test with data curator app; merge develop in main after that; deploy in production. Please treat as *highest priority* based on requests from DCC and external collaborators.

**Comment by milen-sage** [comment]
technically, I should have pushed this PR to ncihtan since its HTAN specific; but I'm waiting out until we finalize our project-specific repos setup

**Comment by milen-sage** [comment]
@xdoan note the schema labels we can generate manifests for are:
- Biospecimen
- OtherAssay

OtherAssay generates a minimal metadata manifest for an assay not covered in the existing RFCs.

**Comment by xdoan** [comment]
currently testing, @milen-sage to clarify do you mean the schema_name is Biospecimen and OtherAssay or is that the display name you wanted?

**Comment by milen-sage** [comment]
yep, schema_name is Biospecimen and OtherAssay; display name can be more descriptive (e.g. 'Biospecimen - All Tiers', and 'Other Assay Type').

**Comment by xdoan** [comment]
So I'm running into issues bc you are merging into develop and @sujaypatil96 already merged the command line utils stuff that is not compatible with the frontend, so I get errors such as "ModuleNotFoundError: No module named 'schematic.utils.config_utils'"

**Comment by milen-sage** [comment]
yep

**Comment by milen-sage** [comment]
Aside from the above two, here are the additional schema names:

BulkRNA-seqLevel3

BulkWESLevel1
BulkWESLevel2
BulkWESLevel3

ScRNA-seqLevel2
ScRNA-seqLevel3
ScRNA-seqLevel4

ScATAC-seqLevel1

@xdoan you can use the same display name pattern that you already use for assays.

**Review by xdoan — APPROVED** [review]
it technically works, but there needs to be QC of the actual content per schema

**Pull request merged**
