### PR TITLE
Removed validity requirement for unrequired attribute entries, allow users to specify validation rule conformity required for entries, fix DCA disconnect caused by JSON Schema validation errors

### PR DESCRIPTION
**Pull request by GiaJordan**
This PR addresses #941, where invalid entries for unrequired attributes would raise errors and prevent manifest submission. Validation rule violations for unrequired attributes will now raise warnings; this allows users to be notified of invalid entries for unrequired attributes without preventing them from submitting their manifest. Violations in unrequired attributes will also raise warnings when validated with the `JSONSchemaValidator` as well.

This PR also extends the functionality of **all** existing validation rules, and allows their behavior to be more customizable. Based on needs identified in previous discussions with @milen-sage, users can now control whether each validation rule raises an error and prevents manifest submission, or raises a warning and notifies submitters of invalidity. Note that this control only extends to validation rules, and not `JSONSchema` validation like `valid values`. Specification of errors or warnings is not necessary, as each rule has a default message type that it will raise in the absence of explicit specification.

Information about each rule and the default message each raises will be added to [SchemaHub](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2645262364/Data+Model+Validation+Rules) in #1002.

### CODE REVIEW

**Review by milen-sage — APPROVED** [review]
Thanks @GiaJordan !

**Review by linglp — APPROVED** [review]

**Comment by milen-sage** [comment]
@GiaJordan perhaps before we merge this PR in `develop` we could first merge the fixes for these two issues as hot fixes:

- https://sagebionetworks.jira.com/browse/IBCSPRT-100
- https://sagebionetworks.jira.com/browse/IBCSPRT-99

That way we'd have more time to test this PR. What do you think?

**Comment by GiaJordan** [comment]
@milen-sage can you grant me access to those issues or the project so I can view?

**Comment by milen-sage** [comment]
Hmm, I tried to add you yesterday - you didn't receive an invite email?

**Comment by GiaJordan** [comment]
@milen-sage I don't think so; I'm not seeing one in my inbox or spam folders

**Comment by milen-sage** [comment]
Ok, I sent a request and will keep you posted.

**Comment by GiaJordan** [comment]
I'll look out for it

**Comment by milen-sage** [comment]
@GiaJordan you should have access to Jira now - thanks!

**Comment by GiaJordan** [comment]
Thanks @milen-sage, confirming I do have access to the linked issues. If possible, could you also add me to the HTAN project so I can view the other issue linked in these?

**Comment by milen-sage** [comment]
Just sent a request for the HTAN project as well.

**Comment by GiaJordan** [comment]
https://sagebionetworks.jira.com/browse/IBCSPRT-100 addressed in #1006

**Comment by GiaJordan** [comment]
Tech debt payed in this PR will address https://sagebionetworks.jira.com/browse/IBCSPRT-99 as well

**Pull request merged**
