### PR TITLE
make api packages optional

### PR DESCRIPTION
**Pull request by andrewelamb**
- fixes [fds-1323](https://sagebionetworks.jira.com/browse/FDS-1323)
- makes api packages optional

### CODE REVIEW

**Comment by andrewelamb** [comment]
@linglp did I get all the api-specif packages?

Is there anywhere (like the API) we need to make sure the api packages are being installed? The testing workflows are already set.

**Review by linglp — COMMENTED** [review]
I think `Jinja2` and `uwsgi` package are only related to schematic API as well, so they could also be optional. Instead of having API dependencies as "extras", I think it makes more sense to manage API dependencies as a `group`: https://python-poetry.org/docs/master/managing-dependencies/

**Comment by andrewelamb** [comment]
@linglp Do you know if `poetry install --all-extras` still works with groups, or do you have to use something else?

**Comment by linglp** [comment]
@andrewelamb Followup to our discussion in code review, I think the `group` approach will work like this: 

[tool.poetry.group.api]
optional = true

[tool.poetry.group.api.dependencies]
connexion = {extras = ["swagger-ui"], version = "^2.8.0"}
Flask = "^2.0.0"
Flask-Cors = "^3.0.10"
uWSGI = "^2.0.21"
Jinja2 = ">2.11.3"

and also you should remove those packages that are previously under section `[tool.poetry.dependencies]`


And when testing it out, I am seeing: 
```
(schematicpy-py3.10) lpeng@w153 schematic % poetry install --with api   
Configuration file exists at /Users/lpeng/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/lpeng/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Package operations: 7 installs, 0 updates, 0 removals

  • Installing werkzeug (2.1.2)
  • Installing clickclick (20.10.2)
  • Installing flask (2.1.3)
  • Installing swagger-ui-bundle (0.0.9)
  • Installing connexion (2.14.2)
  • Installing flask-cors (3.0.10)
  • Installing uwsgi (2.0.23)

```

and also: 
```
(schematicpy-py3.10) lpeng@w153 schematic % poetry install --without api
Configuration file exists at /Users/lpeng/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/lpeng/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.

Package operations: 0 installs, 0 updates, 7 removals

  • Removing clickclick (20.10.2)
  • Removing connexion (2.14.2)
  • Removing flask (2.1.3)
  • Removing flask-cors (3.0.10)
  • Removing swagger-ui-bundle (0.0.9)
  • Removing uwsgi (2.0.23)
  • Removing werkzeug (2.1.2)

Installing the current project: schematicpy (23.11.1)

```

**Review by linglp — CHANGES_REQUESTED** [review]
Just like we discussed in code review, it will be better to organize dependencies using `group`. Could you update the ReadMe documentation, the github workflow and toml file? Thank you!!

**Comment by andrewelamb** [comment]
@linglp this mostly worked. I must have not had the toml quite correct. I am seeing this:

```poetry install --with api 
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing uwsgi (2.0.21): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
```

But maybe thats just on my laptop.

**Comment by linglp** [comment]
@andrewelamb I think I just remembered that @GiaJordan had problems of installing `uwsgi` package on windows machine. Could you confirm with Gianna? If so, can we have two separate optional groups? One group is for `aws` that only contain uwsgi package, and one group is for `api` that contains the rest of the API packages. To make sure that users who are using the APIs locally could install required packages to run APIs, they could do `poetry install --with api`, and for users who are going to test out APIs locally with docker and uwsgi, they could do `poetry install --with api, aws`

**Comment by GiaJordan** [comment]
> @andrewelamb I think I just remembered that @GiaJordan had problems of installing `uwsgi` package on windows machine. Could you confirm with Gianna? 

That is correct @linglp

**Review by linglp — CHANGES_REQUESTED** [review]
@andrewelamb I tried again but `poetry install --without api` is no longer working for me. I looked into the lock file, and I think there are some changes there are concerning, for example, for some reasons, uwsgi version gets downgraded from `"2.0.23"` to `"2.0.21"`, and also I saw that `flask` is showing up as "required" in the lock: 
```
[[package]]
name = "flask"
version = "2.1.3"
description = "A simple framework for building complex web applications."
optional = false
python-versions = ">=3.7"
files = [
    {file = "Flask-2.1.3-py3-none-any.whl", hash = "sha256:9013281a7402ad527f8fd56375164f3aa021ecfaff89bfe3825346c24f87e04c"},
    {file = "Flask-2.1.3.tar.gz", hash = "sha256:15972e5017df0575c3d6c090ba168b6db90259e620ac8d7ea813a396bad5b6cb"},
]

same for other flask API related packages like `flask-cors`

I think since those packages are showing up as "required" in the lock, `poetry install --with api` and `poetry install --without api` are not working properly. I think there might be something wrong when you generate the lock file or resolve merge conflicts. Could you double check? If your environment doesn't work, I advise creating a github code space for your branch and see if you could get those commands to work there. For more info about github code space, you could check: https://docs.github.com/en/codespaces/developing-in-a-codespace/creating-a-codespace-for-a-repository#creating-a-codespace-for-a-repository

**Comment by andrewelamb** [comment]
@linglp I tried doing this with my new laptop and got the same lock file. This is actually a known issue when using [poetry groups](https://github.com/python-poetry/poetry/issues/7747)

This did not happen with extras. See [here](https://github.com/Sage-Bionetworks/schematic/blob/7250aadad3e80f896e2fe4c7f8236bf9aab60b78/poetry.lock#L961) and [here](https://github.com/Sage-Bionetworks/schematic/blob/7250aadad3e80f896e2fe4c7f8236bf9aab60b78/poetry.lock#L4547)

I would vote for going back to extras. Is there an advantage to using groups over extras? I use extras in schematic db for the optional packages and it works just fine.

**Comment by linglp** [comment]
@andrewelamb it makes sense to switch back to use `--extras` since we have trouble with `group`. I also saw this issue: https://github.com/python-poetry/poetry/issues/3188 which seems to be related to our problem as well.

**Comment by andrewelamb** [comment]
@linglp I went back to extras, but put uwsgi in its own group.

**Review by linglp — APPROVED** [review]
I think it is now working for me. Thanks for the fix. See testing details: 
```
@linglp ➜ /workspaces/schematic (feature-fds-1323-api-packages-optional) $ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 0 updates, 7 removals

  • Removing clickclick (20.10.2)
  • Removing connexion (2.14.2)
  • Removing flask (2.1.3)
  • Removing flask-cors (3.0.10)
  • Removing swagger-ui-bundle (0.0.9)
  • Removing uwsgi (2.0.24)
  • Removing werkzeug (2.1.2)

Installing the current project: schematicpy (23.11.1)
@linglp ➜ /workspaces/schematic (feature-fds-1323-api-packages-optional) $ poetry install --all-extras
Installing dependencies from lock file

Package operations: 7 installs, 0 updates, 0 removals

  • Installing werkzeug (2.1.2)
  • Installing clickclick (20.10.2)
  • Installing flask (2.1.3)
  • Installing swagger-ui-bundle (0.0.9)
  • Installing connexion (2.14.2)
  • Installing flask-cors (3.0.10)
  • Installing uwsgi (2.0.24)

Installing the current project: schematicpy (23.11.1)
```
```
linglp ➜ /workspaces/schematic (feature-fds-1323-api-packages-optional) $ poetry install --extras "aws"
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing uwsgi (2.0.24)

Installing the current project: schematicpy (23.11.1)

```

**Pull request merged**
