### PR TITLE
Tests for DataModelRelationships class

### PR DESCRIPTION
**Pull request by andrewelamb**
fixes [fds-1058](https://sagebionetworks.jira.com/browse/FDS-1058)
fixes [fds-1075](https://sagebionetworks.jira.com/browse/FDS-1075)
fixes [fds-1076](https://sagebionetworks.jira.com/browse/FDS-1076)
fixes [fds-1077](https://sagebionetworks.jira.com/browse/FDS-1077)
fixes [fds-1078](https://sagebionetworks.jira.com/browse/FDS-1078)

### CODE REVIEW

**Comment by andrewelamb** [comment]
@mialy-defelice Some comments:

```
for k, v in self.relationships_dictionary.items():
            try:
                if v['required_header']:
                    required_headers.append(v['csv_header'])
            except KeyError:
                print(f"Did not provide a 'required_header' key, value pair for the nested dictionary {k} : {key}")
```
I'm not entire sure what the intention of these code blocks are.  If I'm not mistaken, you will never get a `KeyError` because `v['required_header']` is in an `if` statement. If `'required_header'` isn't in `v` if it simply resolve as `False` and nothing will happen. 

In the f-string `f"Did not provide a 'required_header' key, value pair for the nested dictionary {k} : {key}"` There doesn't appear to be  a variable named `key`, should that be `v`?

I would change these blocks to:

```
for k, v in self.relationships_dictionary.items():
            if v['required_header']:
                required_headers.append(v['csv_header'])
            else
                print(f"Did not provide a 'required_header' key, value pair for the nested dictionary {k} : {v}")
```

**Comment by andrewelamb** [comment]
@mialy-defelice Since this class and its methods don't take any variables I wasn't sure what to test. I wrote some to basically make sure the methods run and the return non-empty outputs. As the comment above describes I think the `KeyValue` errors are impossible to trigger, I didn't write anything that tests them. Let me know if there is anything else you would like me to test for!

**Comment by andrewelamb** [comment]
@mialy-defelice I would also suggest to make this mypy friendly:

```
from typing import Dict # this can be removed
from typing import Any
def define_data_model_relationships(self) -> dict[str, Any]:
def define_required_csv_headers(self) ->  list[str]:
def define_edge_relationships(self) -> dict[str, Optional[str]]:
def define_value_relationships(self)  -> dict[str, Optional[str]]:
```

**Comment by mialy-defelice** [comment]
> @mialy-defelice I would also suggest to make this mypy friendly:
> 
> ```
> from typing import Dict # this can be removed
> from typing import Any
> def define_data_model_relationships(self) -> dict[str, Any]:
> def define_required_csv_headers(self) ->  list[str]:
> def define_edge_relationships(self) -> dict[str, Optional[str]]:
> def define_value_relationships(self)  -> dict[str, Optional[str]]:
> ```

Assuming this was a comment for the relationships class, I just added reviewers to that PR, so please feel free to leave tons of comments there!

**Comment by mialy-defelice** [comment]
> @mialy-defelice Since this class and its methods don't take any variables I wasn't sure what to test. I wrote some to basically make sure the methods run and the return non-empty outputs. As the comment above describes I think the `KeyValue` errors are impossible to trigger, I didn't write anything that tests them. Let me know if there is anything else you would like me to test for!

I think the only thing I would add is that for the helper classes like test_define_required_csv_headers that we test the output matches the exact current output. This would help in the instance that someone has accidentally changed something, or goes in and intentionally changes something... which shouldn't be happening. If we intend to add things to the relationships class, we can update the tests.

**Comment by mialy-defelice** [comment]
But other than that it looks good.

**Comment by andrewelamb** [comment]
@mialy-defelice Can I go ahead and merge this?

**Comment by mialy-defelice** [comment]
@andrewelamb so sorry, I didn't see that you added to the tests last week. yep go ahead and merge!

**Pull request merged**
