### PR TITLE
Add Manifest download to the CLI

### PR DESCRIPTION
**Pull request by mialy-defelice**
To match function in the API, add a manifest download option to the CLI along with the new functionality to change the manifest name upon download.

### CODE REVIEW

**Comment by mialy-defelice** [comment]
@mialy-defelice bump to check if this needs to still needs to be pushed.

**Comment by mialy-defelice** [comment]
@AmyHeiser do we want to push this?

**Comment by AmyHeiser** [comment]
It would be nice to add this option, but it's an old PR can you merge without any issues @mialy-defelice ?

**Comment by mialy-defelice** [comment]
@AmyHeiser I was able to resolve the merge conflicts, and it can be pushed.

**Pull request merged**
