### PR TITLE
Develop fds 364 pylint schema module

### PR DESCRIPTION
**Pull request by andrewelamb**
- Fixes [FDS-364]
- Pylints the schemas module

[FDS-364]: https://sagebionetworks.jira.com/browse/FDS-364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mialy-defelice** [comment]
Checked via command line that I could convert the csv to jsonld, jsonld to jsonld and get the same file as the one stored on github. This worked. Running API tests as well.

**Comment by andrewelamb** [comment]
@mialy-defelice Just wanted to check in on this one.

**Comment by mialy-defelice** [comment]
> @mialy-defelice Just wanted to check in on this one.

Hey did you reply to the comments? Im not seeing anything on my end.

**Comment by andrewelamb** [comment]
@mialy-defelice I don't see any comments....

**Comment by mialy-defelice** [comment]
@andrewelamb Oh thats strange. I had a bunch of questions. I can see them on my end, but no responses. I'll go ahead and approve bc they arent critical.

**Review by mialy-defelice — APPROVED** [review]

**Comment by andrewelamb** [comment]
@mialy-defelice What probably happened was that you added the comments, but didn't start the review. You'll see the comments, but noone else will , they will kinda of be like a draft.

**Pull request merged**
